//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Can_MealRecord
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public string MachineCode { get; set; }
        public Nullable<System.DateTime> TimeLog { get; set; }
        public Nullable<System.Guid> LineID { get; set; }
        public Nullable<System.Guid> CateringID { get; set; }
        public Nullable<System.Guid> CanteenID { get; set; }
        public Nullable<System.Guid> MealAllowanceTypeID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<bool> NoWorkDay { get; set; }
        public Nullable<System.DateTime> WorkDay { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
    
        public virtual Can_Canteen Can_Canteen { get; set; }
        public virtual Can_Catering Can_Catering { get; set; }
        public virtual Can_Line Can_Line { get; set; }
        public virtual Can_MealAllowanceTypeSetting Can_MealAllowanceTypeSetting { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual Cat_OrgStructure Cat_OrgStructure { get; set; }
    }
}
