//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Can_Canteen
    {
        public Can_Canteen()
        {
            this.Can_MealRecord = new HashSet<Can_MealRecord>();
            this.Can_Line = new HashSet<Can_Line>();
        }
    
        public System.Guid ID { get; set; }
        public string CanteenCode { get; set; }
        public string CanteenName { get; set; }
        public Nullable<System.Guid> LocationID { get; set; }
        public string Note { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual Can_Location Can_Location { get; set; }
        public virtual ICollection<Can_MealRecord> Can_MealRecord { get; set; }
        public virtual ICollection<Can_Line> Can_Line { get; set; }
    }
}
