//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_WorkPlace
    {
        public Cat_WorkPlace()
        {
            this.Cat_ProductionLine = new HashSet<Cat_ProductionLine>();
            this.Hre_AppendixContract = new HashSet<Hre_AppendixContract>();
            this.Hre_Contract = new HashSet<Hre_Contract>();
            this.Hre_Profile = new HashSet<Hre_Profile>();
            this.Ins_ProfileInsuranceMonthly = new HashSet<Ins_ProfileInsuranceMonthly>();
            this.Ins_ReportD02Item = new HashSet<Ins_ReportD02Item>();
            this.Rec_Candidate = new HashSet<Rec_Candidate>();
            this.Rec_JobVacancy = new HashSet<Rec_JobVacancy>();
            this.Sal_PayrollStatusHistory = new HashSet<Sal_PayrollStatusHistory>();
            this.Sal_PayrollStatus = new HashSet<Sal_PayrollStatus>();
            this.Sys_ConditionApproved = new HashSet<Sys_ConditionApproved>();
            this.Sys_LockObject = new HashSet<Sys_LockObject>();
            this.Hre_CandidateGeneral = new HashSet<Hre_CandidateGeneral>();
        }
    
        public System.Guid ID { get; set; }
        public string WorkPlaceName { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ServerID { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> ProvinceID { get; set; }
        public Nullable<System.Guid> DistrictID { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> RegionID { get; set; }
        public Nullable<double> PriceStandard { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    
        public virtual Cat_District Cat_District { get; set; }
        public virtual ICollection<Cat_ProductionLine> Cat_ProductionLine { get; set; }
        public virtual Cat_Province Cat_Province { get; set; }
        public virtual Cat_Region Cat_Region { get; set; }
        public virtual ICollection<Hre_AppendixContract> Hre_AppendixContract { get; set; }
        public virtual ICollection<Hre_Contract> Hre_Contract { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile { get; set; }
        public virtual ICollection<Ins_ProfileInsuranceMonthly> Ins_ProfileInsuranceMonthly { get; set; }
        public virtual ICollection<Ins_ReportD02Item> Ins_ReportD02Item { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate { get; set; }
        public virtual ICollection<Rec_JobVacancy> Rec_JobVacancy { get; set; }
        public virtual ICollection<Sal_PayrollStatusHistory> Sal_PayrollStatusHistory { get; set; }
        public virtual ICollection<Sal_PayrollStatus> Sal_PayrollStatus { get; set; }
        public virtual ICollection<Sys_ConditionApproved> Sys_ConditionApproved { get; set; }
        public virtual ICollection<Sys_LockObject> Sys_LockObject { get; set; }
        public virtual ICollection<Hre_CandidateGeneral> Hre_CandidateGeneral { get; set; }
    }
}
