//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Skill
    {
        public Cat_Skill()
        {
            this.Cat_SkillTopic = new HashSet<Cat_SkillTopic>();
            this.Hre_ActualSkill = new HashSet<Hre_ActualSkill>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string SkillName { get; set; }
        public string Note { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual ICollection<Cat_SkillTopic> Cat_SkillTopic { get; set; }
        public virtual ICollection<Hre_ActualSkill> Hre_ActualSkill { get; set; }
    }
}
