//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_SalaryClassType
    {
        public Cat_SalaryClassType()
        {
            this.Cat_SalaryClass = new HashSet<Cat_SalaryClass>();
            this.Cat_SalaryRank = new HashSet<Cat_SalaryRank>();
            this.Hre_Contract = new HashSet<Hre_Contract>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string SalaryClassTypeName { get; set; }
        public string Description { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual ICollection<Cat_SalaryClass> Cat_SalaryClass { get; set; }
        public virtual ICollection<Cat_SalaryRank> Cat_SalaryRank { get; set; }
        public virtual ICollection<Hre_Contract> Hre_Contract { get; set; }
    }
}
