//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Country
    {
        public Cat_Country()
        {
            this.Cat_Province = new HashSet<Cat_Province>();
            this.Hre_Address = new HashSet<Hre_Address>();
            this.Hre_BusinessTrip = new HashSet<Hre_BusinessTrip>();
            this.Hre_CandidateHistory = new HashSet<Hre_CandidateHistory>();
            this.Hre_Profile = new HashSet<Hre_Profile>();
            this.Hre_Relatives = new HashSet<Hre_Relatives>();
            this.Hre_VisaInfo = new HashSet<Hre_VisaInfo>();
            this.Rec_Candidate = new HashSet<Rec_Candidate>();
            this.Rec_Candidate1 = new HashSet<Rec_Candidate>();
            this.Rec_Candidate2 = new HashSet<Rec_Candidate>();
            this.Hre_Profile1 = new HashSet<Hre_Profile>();
            this.Hre_Profile2 = new HashSet<Hre_Profile>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string CountryName { get; set; }
        public string CountryNameES { get; set; }
        public string Notes { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual ICollection<Cat_Province> Cat_Province { get; set; }
        public virtual ICollection<Hre_Address> Hre_Address { get; set; }
        public virtual ICollection<Hre_BusinessTrip> Hre_BusinessTrip { get; set; }
        public virtual ICollection<Hre_CandidateHistory> Hre_CandidateHistory { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile { get; set; }
        public virtual ICollection<Hre_Relatives> Hre_Relatives { get; set; }
        public virtual ICollection<Hre_VisaInfo> Hre_VisaInfo { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate1 { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate2 { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile1 { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile2 { get; set; }
    }
}
