//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_ProductItem
    {
        public Cat_ProductItem()
        {
            this.Sal_SalaryDepartment = new HashSet<Sal_SalaryDepartment>();
            this.Sal_SalaryDepartment1 = new HashSet<Sal_SalaryDepartment>();
            this.Hre_ProfileProductItem = new HashSet<Hre_ProfileProductItem>();
            this.Sal_ProductCapacity = new HashSet<Sal_ProductCapacity>();
            this.Sal_Productive = new HashSet<Sal_Productive>();
            this.Sal_ProductSalary = new HashSet<Sal_ProductSalary>();
            this.Sal_SalaryProductLineEmployee = new HashSet<Sal_SalaryProductLineEmployee>();
            this.Sal_SalaryDepartmentProduct = new HashSet<Sal_SalaryDepartmentProduct>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
        public string ProductItemName { get; set; }
        public string Code { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> BonusPrice { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public Nullable<double> RateStage { get; set; }
        public Nullable<double> ProductionTime { get; set; }
        public Nullable<System.Guid> CurrencyID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Cat_Currency Cat_Currency { get; set; }
        public virtual Cat_Product Cat_Product { get; set; }
        public virtual ICollection<Sal_SalaryDepartment> Sal_SalaryDepartment { get; set; }
        public virtual ICollection<Sal_SalaryDepartment> Sal_SalaryDepartment1 { get; set; }
        public virtual ICollection<Hre_ProfileProductItem> Hre_ProfileProductItem { get; set; }
        public virtual ICollection<Sal_ProductCapacity> Sal_ProductCapacity { get; set; }
        public virtual ICollection<Sal_Productive> Sal_Productive { get; set; }
        public virtual ICollection<Sal_ProductSalary> Sal_ProductSalary { get; set; }
        public virtual ICollection<Sal_SalaryProductLineEmployee> Sal_SalaryProductLineEmployee { get; set; }
        public virtual ICollection<Sal_SalaryDepartmentProduct> Sal_SalaryDepartmentProduct { get; set; }
    }
}
