//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_ImportItem
    {
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> ImportID { get; set; }
        public string ChildFieldLevel1 { get; set; }
        public string ChildFieldLevel2 { get; set; }
        public string ExcelField { get; set; }
        public bool AllowNull { get; set; }
        public bool AllowDuplicate { get; set; }
        public Nullable<long> DuplicateGroup { get; set; }
        public string Description { get; set; }
        public string UserCreate { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<int> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<bool> IsDefaultValue { get; set; }
        public string DefaultValue { get; set; }
    
        public virtual Cat_Import Cat_Import { get; set; }
    }
}
