//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Export
    {
        public Cat_Export()
        {
            this.Cat_AppendixContractType = new HashSet<Cat_AppendixContractType>();
            this.Cat_ContractType = new HashSet<Cat_ContractType>();
            this.Cat_ExportItem = new HashSet<Cat_ExportItem>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string ExportName { get; set; }
        public string ScreenName { get; set; }
        public string ObjectName { get; set; }
        public Nullable<long> SheetIndex { get; set; }
        public Nullable<long> StartRowIndex { get; set; }
        public Nullable<long> StartColumnIndex { get; set; }
        public string TemplateFile { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsGroup { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
        public Nullable<bool> IsProtected { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<bool> IsColumnDynamic { get; set; }
        public Nullable<bool> IsSmartMarkers { get; set; }
    
        public virtual ICollection<Cat_AppendixContractType> Cat_AppendixContractType { get; set; }
        public virtual ICollection<Cat_ContractType> Cat_ContractType { get; set; }
        public virtual ICollection<Cat_ExportItem> Cat_ExportItem { get; set; }
    }
}
