//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_KPIBonus
    {
        public Cat_KPIBonus()
        {
            this.Cat_KPIBonusItem = new HashSet<Cat_KPIBonusItem>();
            this.Sal_RevenueForShop = new HashSet<Sal_RevenueForShop>();
            this.Sal_RevenueRecord = new HashSet<Sal_RevenueRecord>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string KPIBonusName { get; set; }
        public string Note { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<bool> IsTotalRevenue { get; set; }
        public Nullable<System.Guid> UnitID { get; set; }
    
        public virtual Cat_Unit Cat_Unit { get; set; }
        public virtual ICollection<Cat_KPIBonusItem> Cat_KPIBonusItem { get; set; }
        public virtual ICollection<Sal_RevenueForShop> Sal_RevenueForShop { get; set; }
        public virtual ICollection<Sal_RevenueRecord> Sal_RevenueRecord { get; set; }
    }
}
