//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_UnusualAllowanceCfg
    {
        public Cat_UnusualAllowanceCfg()
        {
            this.Cat_UnAllowCfgAmount = new HashSet<Cat_UnAllowCfgAmount>();
            this.Cat_UnusualAllowanceCfgPrice = new HashSet<Cat_UnusualAllowanceCfgPrice>();
            this.Sal_UnusualAllowance = new HashSet<Sal_UnusualAllowance>();
        }
    
        public System.Guid ID { get; set; }
        public string UnusualAllowanceCfgName { get; set; }
        public string EDType { get; set; }
        public string Code { get; set; }
        public double Amount { get; set; }
        public bool IsAddToHourlyRate { get; set; }
        public bool IsChargePIT { get; set; }
        public bool IsExcludePayslip { get; set; }
        public string MethodCalculation { get; set; }
        public string Formula { get; set; }
        public string Comment { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Cat_UnAllowCfgAmount> Cat_UnAllowCfgAmount { get; set; }
        public virtual ICollection<Cat_UnusualAllowanceCfgPrice> Cat_UnusualAllowanceCfgPrice { get; set; }
        public virtual ICollection<Sal_UnusualAllowance> Sal_UnusualAllowance { get; set; }
    }
}
