//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_ContractType
    {
        public Cat_ContractType()
        {
            this.Cat_InsuranceConfig = new HashSet<Cat_InsuranceConfig>();
            this.Hre_AppendixContract = new HashSet<Hre_AppendixContract>();
            this.Hre_Contract = new HashSet<Hre_Contract>();
            this.Hre_Contract1 = new HashSet<Hre_Contract>();
            this.Hre_Profile = new HashSet<Hre_Profile>();
            this.Hre_CandidateGeneral = new HashSet<Hre_CandidateGeneral>();
        }
    
        public System.Guid ID { get; set; }
        public string ContractTypeName { get; set; }
        public string Type { get; set; }
        public string UnitTime { get; set; }
        public Nullable<double> ValueTime { get; set; }
        public Nullable<System.Guid> ReportMappingID { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string Code { get; set; }
        public string ContractNextID { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ExportID { get; set; }
        public Nullable<int> ExpiryContractLoop { get; set; }
        public Nullable<int> DayInMonthLoop1 { get; set; }
        public Nullable<int> DayInMonthLoop2 { get; set; }
        public Nullable<int> DayInMonthLoop3 { get; set; }
        public Nullable<int> ExpiryContractDayByDay { get; set; }
        public string EmailToList { get; set; }
        public string EmailOther { get; set; }
        public string Formula { get; set; }
        public Nullable<bool> NoneEndContract { get; set; }
        public Nullable<bool> NoneTypeInsuarance { get; set; }
        public Nullable<bool> IsSocialInsurance { get; set; }
        public Nullable<bool> IsHealthInsurance { get; set; }
        public Nullable<bool> IsUnEmployInsurance { get; set; }
    
        public virtual Cat_Export Cat_Export { get; set; }
        public virtual Cat_ReportMapping Cat_ReportMapping { get; set; }
        public virtual ICollection<Cat_InsuranceConfig> Cat_InsuranceConfig { get; set; }
        public virtual ICollection<Hre_AppendixContract> Hre_AppendixContract { get; set; }
        public virtual ICollection<Hre_Contract> Hre_Contract { get; set; }
        public virtual ICollection<Hre_Contract> Hre_Contract1 { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile { get; set; }
        public virtual ICollection<Hre_CandidateGeneral> Hre_CandidateGeneral { get; set; }
    }
}
