//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_TAMScanReasonMiss
    {
        public Cat_TAMScanReasonMiss()
        {
            this.Att_Workday = new HashSet<Att_Workday>();
            this.Can_MealRecordMissing = new HashSet<Can_MealRecordMissing>();
            this.Cat_LeaveDayType = new HashSet<Cat_LeaveDayType>();
        }
    
        public System.Guid ID { get; set; }
        public string TAMScanReasonMissName { get; set; }
        public string Description { get; set; }
        public string IPUpdate { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsRemind { get; set; }
        public Nullable<bool> IsForCMS { get; set; }
        public Nullable<bool> IsFullPay { get; set; }
        public Nullable<System.Guid> MealAllowanceTypeSettingID { get; set; }
    
        public virtual ICollection<Att_Workday> Att_Workday { get; set; }
        public virtual Can_MealAllowanceTypeSetting Can_MealAllowanceTypeSetting { get; set; }
        public virtual ICollection<Can_MealRecordMissing> Can_MealRecordMissing { get; set; }
        public virtual ICollection<Cat_LeaveDayType> Cat_LeaveDayType { get; set; }
    }
}
