//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_NonConformingRecord
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public Nullable<System.Guid> ClassID { get; set; }
        public string ErrorCode { get; set; }
        public string NonConformingRecordName { get; set; }
        public Nullable<System.Guid> ProductLineID { get; set; }
        public Nullable<System.Guid> ProcessID { get; set; }
        public string UserCreate { get; set; }
        public string ServerCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string UserUpdate { get; set; }
        public string ServerUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> ResultXMLID { get; set; }
        public Nullable<System.Guid> TraineeID { get; set; }
        public string Description { get; set; }
    
        public virtual Cat_ProductionLine Cat_ProductionLine { get; set; }
        public virtual Tra_Trainee Tra_Trainee { get; set; }
        public virtual Cat_Process Cat_Process { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual Tra_Class Tra_Class { get; set; }
    }
}
