//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_SalaryJobGroup
    {
        public Cat_SalaryJobGroup()
        {
            this.Cat_JobTitle = new HashSet<Cat_JobTitle>();
            this.Cat_SalaryMarketDetail = new HashSet<Cat_SalaryMarketDetail>();
            this.Sal_BasicSalary = new HashSet<Sal_BasicSalary>();
        }
    
        public System.Guid ID { get; set; }
        public string SalaryJobGroupName { get; set; }
        public string Description { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual ICollection<Cat_JobTitle> Cat_JobTitle { get; set; }
        public virtual ICollection<Cat_SalaryMarketDetail> Cat_SalaryMarketDetail { get; set; }
        public virtual ICollection<Sal_BasicSalary> Sal_BasicSalary { get; set; }
    }
}
