//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_SyncItem
    {
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> SyncID { get; set; }
        public string OuterField { get; set; }
        public string InnerField { get; set; }
        public Nullable<bool> AllowNull { get; set; }
        public Nullable<bool> AllowDuplicate { get; set; }
        public Nullable<int> DuplicateGroup { get; set; }
        public string FilterValues { get; set; }
        public Nullable<bool> IsExcluded { get; set; }
        public string Description { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual Cat_Sync Cat_Sync { get; set; }
    }
}
