//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_ReportMapping
    {
        public Cat_ReportMapping()
        {
            this.Cat_AppendixContractType = new HashSet<Cat_AppendixContractType>();
            this.Cat_ContractType = new HashSet<Cat_ContractType>();
            this.Cat_PayrollGroup = new HashSet<Cat_PayrollGroup>();
            this.Cat_PayrollGroup1 = new HashSet<Cat_PayrollGroup>();
            this.Cat_ReportMappingItem = new HashSet<Cat_ReportMappingItem>();
            this.Hre_AppendixContract = new HashSet<Hre_AppendixContract>();
            this.Rep_Master = new HashSet<Rep_Master>();
        }
    
        public System.Guid ID { get; set; }
        public string ReportMappingName { get; set; }
        public string TemplateFile { get; set; }
        public int RowStartIndex { get; set; }
        public string PageName { get; set; }
        public string Type { get; set; }
        public string GroupByField { get; set; }
        public string SumByFieldName { get; set; }
        public string CountByFieldName { get; set; }
        public string AvgByFieldName { get; set; }
        public string HeaderFieldName1 { get; set; }
        public string HeaderCell1 { get; set; }
        public string HeaderFieldName2 { get; set; }
        public string HeaderCell2 { get; set; }
        public string HeaderFieldName3 { get; set; }
        public string HeaderCell3 { get; set; }
        public string HeaderFieldName4 { get; set; }
        public string HeaderCell4 { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string StoreProcedure { get; set; }
        public string OrderByField { get; set; }
        public Nullable<bool> IsSumAll { get; set; }
        public string FromSumAll { get; set; }
        public string ToSumAll { get; set; }
        public Nullable<bool> IsGroup { get; set; }
        public Nullable<bool> IsProtected { get; set; }
        public Nullable<bool> IsReadOnly { get; set; }
        public Nullable<int> SheetIndex { get; set; }
        public Nullable<int> StartColumnIndex { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Cat_AppendixContractType> Cat_AppendixContractType { get; set; }
        public virtual ICollection<Cat_ContractType> Cat_ContractType { get; set; }
        public virtual ICollection<Cat_PayrollGroup> Cat_PayrollGroup { get; set; }
        public virtual ICollection<Cat_PayrollGroup> Cat_PayrollGroup1 { get; set; }
        public virtual ICollection<Cat_ReportMappingItem> Cat_ReportMappingItem { get; set; }
        public virtual ICollection<Hre_AppendixContract> Hre_AppendixContract { get; set; }
        public virtual ICollection<Rep_Master> Rep_Master { get; set; }
    }
}
