//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_PurchaseItems
    {
        public Cat_PurchaseItems()
        {
            this.FIN_PurchaseRequestItem = new HashSet<FIN_PurchaseRequestItem>();
        }
    
        public System.Guid ID { get; set; }
        public string PurchaseItemName { get; set; }
        public string PurchaseItemCode { get; set; }
        public string PurchaseItemCost { get; set; }
        public Nullable<System.Guid> OwnerID { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual Cat_Owner Cat_Owner { get; set; }
        public virtual ICollection<FIN_PurchaseRequestItem> FIN_PurchaseRequestItem { get; set; }
    }
}
