//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_AbilityTile
    {
        public Cat_AbilityTile()
        {
            this.Cat_SalaryClass = new HashSet<Cat_SalaryClass>();
            this.Hre_Profile = new HashSet<Hre_Profile>();
            this.Hre_WorkHistory = new HashSet<Hre_WorkHistory>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> RankID { get; set; }
        public string AbilityTitleVNI { get; set; }
        public string AbilityTitleEng { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Cat_SalaryClass> Cat_SalaryClass { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile { get; set; }
        public virtual ICollection<Hre_WorkHistory> Hre_WorkHistory { get; set; }
    }
}
