//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_HDTJobType
    {
        public Cat_HDTJobType()
        {
            this.Cat_HDTJobTypePrice = new HashSet<Cat_HDTJobTypePrice>();
            this.Hre_HDTJob = new HashSet<Hre_HDTJob>();
        }
    
        public System.Guid ID { get; set; }
        public string HDTJobTypeName { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> HDTJobGroupID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> DateOfEffect { get; set; }
        public string Unit { get; set; }
        public string Dept { get; set; }
        public string Part { get; set; }
        public string Line { get; set; }
        public string Session { get; set; }
        public string Status { get; set; }
        public string EncryptJob { get; set; }
        public string JobType { get; set; }
        public string StandardElement { get; set; }
        public string HDTJobTypeNameHVN { get; set; }
    
        public virtual Cat_HDTJobGroup Cat_HDTJobGroup { get; set; }
        public virtual ICollection<Cat_HDTJobTypePrice> Cat_HDTJobTypePrice { get; set; }
        public virtual ICollection<Hre_HDTJob> Hre_HDTJob { get; set; }
    }
}
