//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_GradeAttendance
    {
        public Cat_GradeAttendance()
        {
            this.Att_Grade = new HashSet<Att_Grade>();
            this.Cat_LateEarlyRule = new HashSet<Cat_LateEarlyRule>();
            this.Cat_GradeCfg = new HashSet<Cat_GradeCfg>();
            this.Hre_CandidateGeneral = new HashSet<Hre_CandidateGeneral>();
        }
    
        public System.Guid ID { get; set; }
        public string GradeAttendanceName { get; set; }
        public string StdWorkDay { get; set; }
        public string StdOvertimeDay { get; set; }
        public Nullable<double> HoursPerDay { get; set; }
        public Nullable<System.DateTime> LeaveDayFrom { get; set; }
        public Nullable<System.DateTime> LeaveDayTo { get; set; }
        public Nullable<System.DateTime> OvertimeFrom { get; set; }
        public Nullable<System.DateTime> OvertimeTo { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string AttendanceMethod { get; set; }
        public Nullable<bool> IsDeductInLateOutEarly { get; set; }
        public string RosterType { get; set; }
        public Nullable<bool> IsLateEarlyRounding { get; set; }
        public Nullable<bool> IsReceiveOvertimeBonus { get; set; }
        public Nullable<bool> IsLateEarlyFirstLastShiftRound { get; set; }
        public Nullable<bool> IsFixedOT { get; set; }
        public Nullable<bool> IsActualOT { get; set; }
        public Nullable<double> OTWorkDayFix { get; set; }
        public Nullable<int> OTWorkdayActual { get; set; }
        public Nullable<System.Guid> WorkOnMondayID { get; set; }
        public Nullable<System.Guid> WorkOnTuesdayID { get; set; }
        public Nullable<System.Guid> WorkOnWednesdayID { get; set; }
        public Nullable<System.Guid> WorkOnThursdayID { get; set; }
        public Nullable<System.Guid> WorkOnFridayID { get; set; }
        public Nullable<System.Guid> WorkOnSaturdayID { get; set; }
        public Nullable<System.Guid> WorkOnSundayID { get; set; }
        public Nullable<bool> IsFixedLeave { get; set; }
        public Nullable<bool> IsActualLeave { get; set; }
        public Nullable<double> LeaveWorkDayFix { get; set; }
        public Nullable<int> LeaveWorkdayActual { get; set; }
        public Nullable<bool> IsRosterLeave { get; set; }
        public Nullable<bool> IsFormulaLeave { get; set; }
        public string LeaveWorkdayFormula { get; set; }
        public Nullable<bool> IsRosterOT { get; set; }
        public Nullable<bool> IsFormulaOT { get; set; }
        public string OTWorkdayFormula { get; set; }
        public Nullable<int> HourOnWorkDate { get; set; }
        public Nullable<bool> ShiftHours { get; set; }
        public Nullable<bool> FixHours { get; set; }
        public Nullable<int> ExpHourPerDay { get; set; }
        public Nullable<System.DateTime> ExpHourFrom { get; set; }
        public Nullable<System.DateTime> ExpHourTo { get; set; }
        public Nullable<bool> LateEarly { get; set; }
        public Nullable<bool> RoundByLateEarly { get; set; }
        public Nullable<bool> Round { get; set; }
        public Nullable<bool> RoundByMonth { get; set; }
        public Nullable<int> TotalDayAnnualLeaveOnYear { get; set; }
        public string FormulaAnnualLeave { get; set; }
        public Nullable<System.Guid> OTNomal { get; set; }
        public Nullable<System.Guid> OTLeaveDay { get; set; }
        public Nullable<System.Guid> OTHoliday { get; set; }
        public Nullable<System.Guid> OTNomalNight { get; set; }
        public Nullable<System.Guid> OTLeaveDayNight { get; set; }
        public Nullable<System.Guid> OTHolidayNight { get; set; }
        public Nullable<int> Seniority { get; set; }
        public string OptionReceive { get; set; }
        public Nullable<bool> IsApplySubSalaryNewQuitEmp { get; set; }
        public Nullable<double> MinWorkDayNewQuitEmp { get; set; }
        public Nullable<double> RateUneven { get; set; }
        public Nullable<int> MinWorkDay { get; set; }
        public string EDType { get; set; }
        public Nullable<bool> IsMonthlyMidCutOff { get; set; }
        public string SalaryTimeType { get; set; }
        public Nullable<int> SalaryTimeDay { get; set; }
        public string DurationType { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public Nullable<int> MidCutOffDay { get; set; }
        public Nullable<bool> IsDurationCutOff { get; set; }
        public Nullable<int> SalaryLeaveTimeDay { get; set; }
        public string SalaryLeaveTimeType { get; set; }
        public string MethodPayment { get; set; }
    
        public virtual ICollection<Att_Grade> Att_Grade { get; set; }
        public virtual ICollection<Cat_LateEarlyRule> Cat_LateEarlyRule { get; set; }
        public virtual ICollection<Cat_GradeCfg> Cat_GradeCfg { get; set; }
        public virtual ICollection<Hre_CandidateGeneral> Hre_CandidateGeneral { get; set; }
    }
}
