//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_UsualAllowance
    {
        public Cat_UsualAllowance()
        {
            this.Cat_GradeAllowance = new HashSet<Cat_GradeAllowance>();
            this.Cat_JobTitleAllowance = new HashSet<Cat_JobTitleAllowance>();
            this.Cat_UsualAllowanceLevel = new HashSet<Cat_UsualAllowanceLevel>();
            this.Hre_AppendixContract = new HashSet<Hre_AppendixContract>();
            this.Hre_AppendixContract1 = new HashSet<Hre_AppendixContract>();
            this.Hre_AppendixContract2 = new HashSet<Hre_AppendixContract>();
            this.Hre_AppendixContract3 = new HashSet<Hre_AppendixContract>();
            this.Hre_AppendixContract4 = new HashSet<Hre_AppendixContract>();
            this.Hre_CandidateGeneral = new HashSet<Hre_CandidateGeneral>();
            this.Hre_CandidateGeneral1 = new HashSet<Hre_CandidateGeneral>();
            this.Hre_CandidateGeneral2 = new HashSet<Hre_CandidateGeneral>();
            this.Hre_CandidateGeneral3 = new HashSet<Hre_CandidateGeneral>();
            this.Hre_CandidateGeneral4 = new HashSet<Hre_CandidateGeneral>();
            this.Hre_Contract = new HashSet<Hre_Contract>();
            this.Hre_Contract1 = new HashSet<Hre_Contract>();
            this.Hre_Contract2 = new HashSet<Hre_Contract>();
            this.Hre_Contract3 = new HashSet<Hre_Contract>();
            this.Hre_Contract4 = new HashSet<Hre_Contract>();
            this.Hre_Contract5 = new HashSet<Hre_Contract>();
            this.Rec_Candidate = new HashSet<Rec_Candidate>();
            this.Rec_Candidate1 = new HashSet<Rec_Candidate>();
            this.Rec_Candidate2 = new HashSet<Rec_Candidate>();
            this.Rec_Candidate3 = new HashSet<Rec_Candidate>();
            this.Rec_RecruitmentHistory = new HashSet<Rec_RecruitmentHistory>();
            this.Rec_RecruitmentHistory1 = new HashSet<Rec_RecruitmentHistory>();
            this.Rec_RecruitmentHistory2 = new HashSet<Rec_RecruitmentHistory>();
            this.Rec_RecruitmentHistory3 = new HashSet<Rec_RecruitmentHistory>();
            this.Sal_BasicSalary = new HashSet<Sal_BasicSalary>();
            this.Sal_BasicSalary1 = new HashSet<Sal_BasicSalary>();
            this.Sal_BasicSalary2 = new HashSet<Sal_BasicSalary>();
            this.Sal_BasicSalary3 = new HashSet<Sal_BasicSalary>();
            this.Sal_BasicSalary4 = new HashSet<Sal_BasicSalary>();
            this.Sal_BasicSalary5 = new HashSet<Sal_BasicSalary>();
            this.Sal_GradeAllowance = new HashSet<Sal_GradeAllowance>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
        public string UsualAllowanceName { get; set; }
        public string Code { get; set; }
        public string EDType { get; set; }
        public bool IsAddToHourlyRate { get; set; }
        public bool IsChargePIT { get; set; }
        public bool IsBaseOnWorkday { get; set; }
        public Nullable<double> MinHours { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<bool> UseSalaryByHours { get; set; }
        public string MethodPayroll { get; set; }
        public Nullable<bool> IsUseHoursSalary { get; set; }
        public string Formula { get; set; }
        public string MethodCalculation { get; set; }
        public string FormulaNoPIT { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Cat_GradeAllowance> Cat_GradeAllowance { get; set; }
        public virtual ICollection<Cat_JobTitleAllowance> Cat_JobTitleAllowance { get; set; }
        public virtual ICollection<Cat_UsualAllowanceLevel> Cat_UsualAllowanceLevel { get; set; }
        public virtual ICollection<Hre_AppendixContract> Hre_AppendixContract { get; set; }
        public virtual ICollection<Hre_AppendixContract> Hre_AppendixContract1 { get; set; }
        public virtual ICollection<Hre_AppendixContract> Hre_AppendixContract2 { get; set; }
        public virtual ICollection<Hre_AppendixContract> Hre_AppendixContract3 { get; set; }
        public virtual ICollection<Hre_AppendixContract> Hre_AppendixContract4 { get; set; }
        public virtual ICollection<Hre_CandidateGeneral> Hre_CandidateGeneral { get; set; }
        public virtual ICollection<Hre_CandidateGeneral> Hre_CandidateGeneral1 { get; set; }
        public virtual ICollection<Hre_CandidateGeneral> Hre_CandidateGeneral2 { get; set; }
        public virtual ICollection<Hre_CandidateGeneral> Hre_CandidateGeneral3 { get; set; }
        public virtual ICollection<Hre_CandidateGeneral> Hre_CandidateGeneral4 { get; set; }
        public virtual ICollection<Hre_Contract> Hre_Contract { get; set; }
        public virtual ICollection<Hre_Contract> Hre_Contract1 { get; set; }
        public virtual ICollection<Hre_Contract> Hre_Contract2 { get; set; }
        public virtual ICollection<Hre_Contract> Hre_Contract3 { get; set; }
        public virtual ICollection<Hre_Contract> Hre_Contract4 { get; set; }
        public virtual ICollection<Hre_Contract> Hre_Contract5 { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate1 { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate2 { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate3 { get; set; }
        public virtual ICollection<Rec_RecruitmentHistory> Rec_RecruitmentHistory { get; set; }
        public virtual ICollection<Rec_RecruitmentHistory> Rec_RecruitmentHistory1 { get; set; }
        public virtual ICollection<Rec_RecruitmentHistory> Rec_RecruitmentHistory2 { get; set; }
        public virtual ICollection<Rec_RecruitmentHistory> Rec_RecruitmentHistory3 { get; set; }
        public virtual ICollection<Sal_BasicSalary> Sal_BasicSalary { get; set; }
        public virtual ICollection<Sal_BasicSalary> Sal_BasicSalary1 { get; set; }
        public virtual ICollection<Sal_BasicSalary> Sal_BasicSalary2 { get; set; }
        public virtual ICollection<Sal_BasicSalary> Sal_BasicSalary3 { get; set; }
        public virtual ICollection<Sal_BasicSalary> Sal_BasicSalary4 { get; set; }
        public virtual ICollection<Sal_BasicSalary> Sal_BasicSalary5 { get; set; }
        public virtual ICollection<Sal_GradeAllowance> Sal_GradeAllowance { get; set; }
    }
}
