//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_OrgMoreInfor
    {
        public System.Guid ID { get; set; }
        public string ServicesType { get; set; }
        public Nullable<System.DateTime> ContractFrom { get; set; }
        public Nullable<System.DateTime> ContractTo { get; set; }
        public string BillingCompanyName { get; set; }
        public string BillingAddress { get; set; }
        public string TaxCode { get; set; }
        public string Description { get; set; }
        public string DurationPay { get; set; }
        public string RecipientInvoice { get; set; }
        public string TelePhone { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
    
        public virtual Cat_OrgStructure Cat_OrgStructure { get; set; }
    }
}
