//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eva_PerformanceForDetail
    {
        public Eva_PerformanceForDetail()
        {
            this.Eva_PerformanceEvaDetail = new HashSet<Eva_PerformanceEvaDetail>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PerformanceID { get; set; }
        public Nullable<System.Guid> KPIID { get; set; }
        public string KPIName { get; set; }
        public Nullable<double> Mark { get; set; }
        public string Evaluation { get; set; }
        public Nullable<int> OrderKPI { get; set; }
        public string Formula { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string DescriptionKPIFix { get; set; }
        public string DescriptionKP { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<double> Rate { get; set; }
    
        public virtual Eva_KPI Eva_KPI { get; set; }
        public virtual Eva_Performance Eva_Performance { get; set; }
        public virtual ICollection<Eva_PerformanceEvaDetail> Eva_PerformanceEvaDetail { get; set; }
    }
}
