//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eva_PerformanceReview
    {
        public Eva_PerformanceReview()
        {
            this.Eva_PerformanceResults = new HashSet<Eva_PerformanceResults>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ProfileID { get; set; }
        public Nullable<System.Guid> SuppervisorProfileID { get; set; }
        public Nullable<System.Guid> ApprovedProfileID { get; set; }
        public System.Guid PerformanceTemplateID { get; set; }
        public Nullable<System.Guid> PerformancePlanID { get; set; }
        public string Status { get; set; }
        public System.DateTime PeriodFromDate { get; set; }
        public System.DateTime PeriodToDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> DatePerformance { get; set; }
        public Nullable<System.DateTime> DateSuppervisor { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<double> TotalPerformanceMark { get; set; }
        public string GoodPerformanceNote { get; set; }
        public string BadPerformanceNote { get; set; }
        public string ResultPerformanceNote { get; set; }
        public Nullable<double> TotalSuppervisorMark { get; set; }
        public string GoodSuppervisorNote { get; set; }
        public string BadSuppervisorNote { get; set; }
        public string ResultSuppervisorNote { get; set; }
        public Nullable<double> TotalApprovedMark { get; set; }
        public string GoodApprovedNote { get; set; }
        public string BadApprovedNote { get; set; }
        public string ResultApprovedNote { get; set; }
        public Nullable<System.Guid> LevelApprovedID { get; set; }
        public string Comment { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> TagID { get; set; }
        public Nullable<double> SalaryIncPercent { get; set; }
        public Nullable<double> DiligentRate { get; set; }
        public Nullable<System.Guid> LevelID { get; set; }
        public Nullable<System.Guid> LevelFirstApproveID { get; set; }
        public string FileUpload { get; set; }
    
        public virtual Eva_Level Eva_Level { get; set; }
        public virtual Eva_Level Eva_Level1 { get; set; }
        public virtual Eva_Level Eva_Level2 { get; set; }
        public virtual Eva_PerformancePlan Eva_PerformancePlan { get; set; }
        public virtual ICollection<Eva_PerformanceResults> Eva_PerformanceResults { get; set; }
        public virtual Eva_PerformanceTemplate Eva_PerformanceTemplate { get; set; }
        public virtual Eva_TagEva Eva_TagEva { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual Hre_Profile Hre_Profile1 { get; set; }
        public virtual Hre_Profile Hre_Profile2 { get; set; }
    }
}
