//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eva_EvalutionData
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<int> Time { get; set; }
        public string Type { get; set; }
        public Nullable<int> C1 { get; set; }
        public Nullable<int> C2 { get; set; }
        public Nullable<int> C3 { get; set; }
        public Nullable<int> C4 { get; set; }
        public Nullable<int> C5 { get; set; }
        public Nullable<int> C6 { get; set; }
        public Nullable<int> C7 { get; set; }
        public Nullable<int> C8 { get; set; }
        public Nullable<int> C9 { get; set; }
        public Nullable<int> C10 { get; set; }
        public Nullable<int> C11 { get; set; }
        public Nullable<int> C12 { get; set; }
        public Nullable<int> C13 { get; set; }
        public Nullable<int> C14 { get; set; }
        public Nullable<int> C15 { get; set; }
        public Nullable<int> C16 { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string C17 { get; set; }
        public string C18 { get; set; }
        public Nullable<double> C19 { get; set; }
        public Nullable<double> C20 { get; set; }
        public Nullable<double> C21 { get; set; }
        public string C22 { get; set; }
        public Nullable<double> C23 { get; set; }
        public Nullable<double> C24 { get; set; }
        public Nullable<double> C25 { get; set; }
        public Nullable<double> C26 { get; set; }
        public Nullable<double> C27 { get; set; }
        public Nullable<double> C28 { get; set; }
        public Nullable<double> C29 { get; set; }
        public Nullable<double> C30 { get; set; }
        public string C31 { get; set; }
        public Nullable<System.Guid> TimesGetDataID { get; set; }
        public string C32 { get; set; }
        public string C33 { get; set; }
    
        public virtual Cat_NameEntity Cat_NameEntity { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
    }
}
