//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_PurchaseRequest
    {
        public FIN_PurchaseRequest()
        {
            this.FIN_PurchaseRequestItem = new HashSet<FIN_PurchaseRequestItem>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> FunctionID { get; set; }
        public Nullable<System.Guid> BudgetOwnerID { get; set; }
        public Nullable<System.Guid> ChannelID { get; set; }
        public Nullable<System.DateTime> BudgetChargedIn { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> UserApproveID { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> UserCreateID { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> CurrencyID1 { get; set; }
        public Nullable<System.Guid> CurrencyID2 { get; set; }
        public Nullable<int> CurrencyRate1 { get; set; }
        public Nullable<int> CurencryRate2 { get; set; }
    
        public virtual Cat_Currency Cat_Currency { get; set; }
        public virtual Cat_Currency Cat_Currency1 { get; set; }
        public virtual Cat_Owner Cat_Owner { get; set; }
        public virtual Cat_Owner Cat_Owner1 { get; set; }
        public virtual Cat_Owner Cat_Owner2 { get; set; }
        public virtual Cat_Supplier Cat_Supplier { get; set; }
        public virtual ICollection<FIN_PurchaseRequestItem> FIN_PurchaseRequestItem { get; set; }
        public virtual Sys_UserApprove Sys_UserApprove { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo { get; set; }
    }
}
