//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_TravelRequestItem
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TravelRequestID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string Description4 { get; set; }
        public Nullable<double> Amount { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string TravelRequestItemName { get; set; }
        public string TravelRequestItemCode { get; set; }
        public Nullable<bool> IsBookingHotel { get; set; }
        public string Departure { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public string Arrival { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public string Mean { get; set; }
        public string Purpose { get; set; }
    
        public virtual FIN_TravelRequest FIN_TravelRequest { get; set; }
    }
}
