//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_HistoryApproveECLAIM
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public Nullable<System.Guid> ClaimID { get; set; }
        public Nullable<System.Guid> TravelRequestID { get; set; }
        public Nullable<System.Guid> CashAdvanceID { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> UserApproveID { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> UserApproveClaimID { get; set; }
    
        public virtual FIN_ApproverECLAIM FIN_ApproverECLAIM { get; set; }
        public virtual Fin_CashAdvance Fin_CashAdvance { get; set; }
        public virtual FIN_Claim FIN_Claim { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual FIN_TravelRequest FIN_TravelRequest { get; set; }
    }
}
