//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hre_Reward
    {
        public System.Guid ID { get; set; }
        public System.Guid ProfileID { get; set; }
        public System.DateTime DateOfIssuance { get; set; }
        public string Reason { get; set; }
        public Nullable<System.Guid> RewardedTitleID { get; set; }
        public Nullable<System.Guid> RewardedDecidingOrgID { get; set; }
        public Nullable<System.Guid> RewardedTimeID { get; set; }
        public Nullable<System.DateTime> DateOfEffective { get; set; }
        public string Description { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> UserApproveID { get; set; }
        public string Requester { get; set; }
        public Nullable<System.Guid> RequesterID { get; set; }
        public Nullable<double> RewardValue { get; set; }
        public string NoOfReward { get; set; }
        public Nullable<System.Guid> RewardedTypeID { get; set; }
        public string Attachment { get; set; }
    
        public virtual Cat_RewardedDecidingOrgs Cat_RewardedDecidingOrgs { get; set; }
        public virtual Cat_RewardedTime Cat_RewardedTime { get; set; }
        public virtual Cat_RewardedTitles Cat_RewardedTitles { get; set; }
        public virtual Cat_RewardedType Cat_RewardedType { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo { get; set; }
    }
}
