//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hre_ProfilePartyUnion
    {
        public System.Guid ID { get; set; }
        public System.Guid ProfileID { get; set; }
        public Nullable<bool> IsYouthUnionist { get; set; }
        public Nullable<System.DateTime> YouthUnionEnrolledDate { get; set; }
        public Nullable<System.Guid> YouthUnionPositionID { get; set; }
        public Nullable<bool> IsCommunistPartyMember { get; set; }
        public Nullable<System.DateTime> CommunistPartyEnrolledDate { get; set; }
        public Nullable<System.Guid> CommunistPartyPositionID { get; set; }
        public string CommunistPartyCardNo { get; set; }
        public Nullable<System.Guid> WoundedSoldierTypeID { get; set; }
        public Nullable<System.Guid> PoliticalLevelID { get; set; }
        public Nullable<bool> IsTradeUnionist { get; set; }
        public Nullable<System.DateTime> TradeUnionistEnrolledDate { get; set; }
        public Nullable<System.Guid> TradeUnionistPositionID { get; set; }
        public Nullable<bool> IsSelfDefenceMilitia { get; set; }
        public Nullable<System.DateTime> SelfDefenceMilitiaEnrolledDate { get; set; }
        public Nullable<System.DateTime> SelfDefenceMilitiaEndDate { get; set; }
        public Nullable<System.Guid> SelfDefenceMilitiaPositionID { get; set; }
        public Nullable<bool> IsVeteranUnionist { get; set; }
        public Nullable<System.DateTime> VeteranUnionEnrolledDate { get; set; }
        public string VeteranUnionCardNo { get; set; }
        public Nullable<System.Guid> VeteranUnionPositionID { get; set; }
        public Nullable<System.DateTime> RevolutionEnrolledDate { get; set; }
        public Nullable<System.DateTime> RevolutionEndDate { get; set; }
        public Nullable<System.Guid> ArmedForceTypeID { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string RelationWithMartyr { get; set; }
        public string Biography { get; set; }
        public Nullable<System.DateTime> CommunistPartyReserveDate { get; set; }
        public Nullable<bool> IsRelationWithMartyr { get; set; }
        public string PoliticalTheory { get; set; }
    
        public virtual Cat_ArmedForceTypes Cat_ArmedForceTypes { get; set; }
        public virtual Cat_CommunistPartyPosition Cat_CommunistPartyPosition { get; set; }
        public virtual Cat_PoliticalLevel Cat_PoliticalLevel { get; set; }
        public virtual Cat_SelfDefenceMilitiaPosition Cat_SelfDefenceMilitiaPosition { get; set; }
        public virtual Cat_TradeUnionistPosition Cat_TradeUnionistPosition { get; set; }
        public virtual Cat_VeteranUnionPosition Cat_VeteranUnionPosition { get; set; }
        public virtual Cat_WoundedSoldierTypes Cat_WoundedSoldierTypes { get; set; }
        public virtual Cat_YouthUnionPosition Cat_YouthUnionPosition { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
    }
}
