//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hre_ArchiveProfile
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public string ProfileName { get; set; }
        public string NameFamily { get; set; }
        public string FirstName { get; set; }
        public string NameEnglish { get; set; }
        public string ImagePath { get; set; }
        public string CodeEmp { get; set; }
        public string CodeTax { get; set; }
        public string CodeAttendance { get; set; }
        public string StatusSyn { get; set; }
        public Nullable<System.DateTime> DateHire { get; set; }
        public Nullable<System.DateTime> DateEndProbation { get; set; }
        public Nullable<System.DateTime> DateQuit { get; set; }
        public Nullable<System.Guid> ResignReasonID { get; set; }
        public string ResignDescription { get; set; }
        public Nullable<System.Guid> CandidateID { get; set; }
        public Nullable<System.Guid> WorkGroupID { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
        public Nullable<System.Guid> PositionID { get; set; }
        public Nullable<System.DateTime> DateOfEffect { get; set; }
        public Nullable<System.Guid> CostCentreID { get; set; }
        public Nullable<System.Guid> EmployeeTypeID { get; set; }
        public string LaborType { get; set; }
        public string WorkingPlace { get; set; }
        public string Supervisor { get; set; }
        public string SocialInsNo { get; set; }
        public Nullable<System.DateTime> SocialInsIssueDate { get; set; }
        public string SocialInsIssuePlace { get; set; }
        public string HealthInsNo { get; set; }
        public Nullable<System.DateTime> HealthInsIssueDate { get; set; }
        public string HealthInsIssuePlace { get; set; }
        public string HealthTreatmentPlace { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<System.Guid> NationalityID { get; set; }
        public Nullable<System.Guid> EthnicID { get; set; }
        public Nullable<System.Guid> ReligionID { get; set; }
        public string BloodType { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public string IDNo { get; set; }
        public Nullable<System.DateTime> IDDateOfIssue { get; set; }
        public string IDPlaceOfIssue { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportDateOfExpiry { get; set; }
        public Nullable<System.DateTime> PassportDateOfIssue { get; set; }
        public string PassportPlaceOfIssue { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Cellphone { get; set; }
        public string HomePhone { get; set; }
        public string BusinessPhone { get; set; }
        public string PAStreet { get; set; }
        public Nullable<System.Guid> PADistrictID { get; set; }
        public Nullable<System.Guid> PACityID { get; set; }
        public string TAStreet { get; set; }
        public Nullable<System.Guid> TADistrictID { get; set; }
        public Nullable<System.Guid> TACityID { get; set; }
        public string StatusVerify { get; set; }
        public Nullable<System.Guid> JobTitleID { get; set; }
        public string LabourNo { get; set; }
        public Nullable<System.DateTime> LabourIssueDate { get; set; }
        public Nullable<System.Guid> PayrollGroupID { get; set; }
        public string LaborBookNo { get; set; }
        public Nullable<System.DateTime> LaborBookIssueDate { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.Guid> EmpTypeID { get; set; }
        public Nullable<System.Guid> ResReasonID { get; set; }
        public string MarriageStatus { get; set; }
        public string ContactName1 { get; set; }
        public string ContactName2 { get; set; }
        public string ContactRelation1 { get; set; }
        public string ContactRelation2 { get; set; }
        public string ContactPhone1 { get; set; }
        public string ContactPhone2 { get; set; }
        public string ContactAddress1 { get; set; }
        public string ContactAddress2 { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    }
}
