//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hre_ProfileMove
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> OldOrgStructureID { get; set; }
        public Nullable<System.Guid> OldTaskID { get; set; }
        public Nullable<System.Guid> NewOrgStructureID { get; set; }
        public Nullable<System.Guid> NewTaskID { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual Cat_OrgStructure Cat_OrgStructure { get; set; }
        public virtual Cat_OrgStructure Cat_OrgStructure1 { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
    }
}
