//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ins_ReportD02
    {
        public Ins_ReportD02()
        {
            this.Ins_ReportD02Item = new HashSet<Ins_ReportD02Item>();
        }
    
        public System.Guid ID { get; set; }
        public string ReportD02Name { get; set; }
        public Nullable<System.DateTime> DateReport { get; set; }
        public Nullable<System.DateTime> DateMonth { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> SociaInsCountPro { get; set; }
        public Nullable<double> SociaInsTotalSalary { get; set; }
        public Nullable<int> HealthInsCountPro { get; set; }
        public Nullable<double> HealthInsTotalSalary { get; set; }
        public Nullable<int> UnEmpInsCountPro { get; set; }
        public Nullable<double> UnEmpInsTotalSalary { get; set; }
        public Nullable<double> MaxSalary { get; set; }
        public Nullable<double> MinSalary { get; set; }
        public Nullable<System.DateTime> DateOfEffectMax { get; set; }
        public Nullable<System.DateTime> DateOfEffectMin { get; set; }
        public string Type { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> PayBackID { get; set; }
    
        public virtual Ins_InsuranceSalaryPayback Ins_InsuranceSalaryPayback { get; set; }
        public virtual ICollection<Ins_ReportD02Item> Ins_ReportD02Item { get; set; }
    }
}
