//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kai_KaizenData
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public string KaizenName { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public Nullable<double> MarkIdea { get; set; }
        public Nullable<double> AmountIdea { get; set; }
        public Nullable<double> MarkPerform { get; set; }
        public Nullable<double> AmountPerform { get; set; }
        public Nullable<double> SumMark { get; set; }
        public Nullable<double> SumAmount { get; set; }
        public Nullable<double> Accumulate { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string CategoryList { get; set; }
        public Nullable<double> AmountTransfered { get; set; }
        public Nullable<System.DateTime> DateTransferPayment { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
        public string OrgStructureName { get; set; }
        public Nullable<bool> IsPaymentOut { get; set; }
        public Nullable<double> AccumulateRevice { get; set; }
    
        public virtual Cat_OrgStructure Cat_OrgStructure { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual Kai_Category Kai_Category { get; set; }
    }
}
