//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rec_Question
    {
        public Rec_Question()
        {
            this.Rec_ResponseBool = new HashSet<Rec_ResponseBool>();
            this.Rec_ResponseMultiple = new HashSet<Rec_ResponseMultiple>();
            this.Rec_ResponseRank = new HashSet<Rec_ResponseRank>();
            this.Rec_ResponseSingle = new HashSet<Rec_ResponseSingle>();
            this.Rec_ResponseText = new HashSet<Rec_ResponseText>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> QuestionaireID { get; set; }
        public Nullable<System.Guid> QuestionBankID { get; set; }
        public int Position { get; set; }
        public string Code { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<double> Rate { get; set; }
    
        public virtual Rec_Questionaire Rec_Questionaire { get; set; }
        public virtual Rec_QuestionBank Rec_QuestionBank { get; set; }
        public virtual ICollection<Rec_ResponseBool> Rec_ResponseBool { get; set; }
        public virtual ICollection<Rec_ResponseMultiple> Rec_ResponseMultiple { get; set; }
        public virtual ICollection<Rec_ResponseRank> Rec_ResponseRank { get; set; }
        public virtual ICollection<Rec_ResponseSingle> Rec_ResponseSingle { get; set; }
        public virtual ICollection<Rec_ResponseText> Rec_ResponseText { get; set; }
    }
}
