//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rec_InterviewCampaign
    {
        public Rec_InterviewCampaign()
        {
            this.Rec_Interview = new HashSet<Rec_Interview>();
            this.Rec_InterviewCampaignDetail = new HashSet<Rec_InterviewCampaignDetail>();
        }
    
        public System.Guid ID { get; set; }
        public string InterviewCampaignName { get; set; }
        public Nullable<System.DateTime> HoldDate { get; set; }
        public string Code { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateInterviewFrom { get; set; }
        public Nullable<System.DateTime> DateInterviewTo { get; set; }
    
        public virtual ICollection<Rec_Interview> Rec_Interview { get; set; }
        public virtual ICollection<Rec_InterviewCampaignDetail> Rec_InterviewCampaignDetail { get; set; }
    }
}
