//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_PayrollTableItem
    {
        public Sal_PayrollTableItem()
        {
            this.Sal_PayrollTableItem1 = new HashSet<Sal_PayrollTableItem>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid PayrollTableID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ValueType { get; set; }
        public bool IsDecrypt { get; set; }
        public bool IsAddToHourlyRate { get; set; }
        public bool IsChargePIT { get; set; }
        public int OrderNo { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string ElementType { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public Nullable<System.DateTime> MonthYear { get; set; }
        public string Value { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string Description4 { get; set; }
        public Nullable<bool> IsShow { get; set; }
    
        public virtual Sal_PayrollTable Sal_PayrollTable { get; set; }
        public virtual ICollection<Sal_PayrollTableItem> Sal_PayrollTableItem1 { get; set; }
        public virtual Sal_PayrollTableItem Sal_PayrollTableItem2 { get; set; }
    }
}
