//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_HoldSalary
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public Nullable<System.DateTime> MonthSalary { get; set; }
        public Nullable<int> DayLeave { get; set; }
        public Nullable<bool> IsLeaveContinuous { get; set; }
        public Nullable<bool> Terminate { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> MonthEndSalary { get; set; }
        public Nullable<double> AmountSalary { get; set; }
        public Nullable<bool> IsLeaveM { get; set; }
        public Nullable<System.Guid> TimeAnalyzeID { get; set; }
        public Nullable<double> AmountSalaryAfterTax { get; set; }
    
        public virtual Cat_NameEntity Cat_NameEntity { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
    }
}
