//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_SchemesStructure
    {
        public Sal_SchemesStructure()
        {
            this.Sal_SchemesProfile = new HashSet<Sal_SchemesProfile>();
        }
    
        public System.Guid ID { get; set; }
        public string SchemesStructureName { get; set; }
        public Nullable<double> Percent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public System.Guid OrgStructureID { get; set; }
    
        public virtual Cat_OrgStructure Cat_OrgStructure { get; set; }
        public virtual ICollection<Sal_SchemesProfile> Sal_SchemesProfile { get; set; }
    }
}
