//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_PayCommission
    {
        public Sal_PayCommission()
        {
            this.Sal_PayCommissionItem = new HashSet<Sal_PayCommissionItem>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public Nullable<System.Guid> CutoffDurationID { get; set; }
        public Nullable<System.DateTime> MonthYear { get; set; }
        public string Status { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> CutoffDuration2ID { get; set; }
    
        public virtual Att_CutOffDuration Att_CutOffDuration { get; set; }
        public virtual Att_CutOffDuration Att_CutOffDuration1 { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual ICollection<Sal_PayCommissionItem> Sal_PayCommissionItem { get; set; }
    }
}
