//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_TimeOffInLieu
    {
        public System.Guid ID { get; set; }
        public System.Guid ProfileID { get; set; }
        public string Type { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> AccumulateLeaves { get; set; }
        public Nullable<double> UnusualLeaves { get; set; }
        public Nullable<double> TakenLeaves { get; set; }
        public Nullable<double> RemainLeaves { get; set; }
        public Nullable<System.Guid> OvertimeID { get; set; }
        public Nullable<System.Guid> LeaveDayID { get; set; }
        public Nullable<System.DateTime> DateApprove { get; set; }
        public string Notes { get; set; }
        public string OTRate { get; set; }
        public Nullable<double> OTHours { get; set; }
        public Nullable<double> LeaveHours { get; set; }
        public Nullable<double> ConvertedCashHours { get; set; }
        public Nullable<double> BalanceHours { get; set; }
        public Nullable<System.DateTime> CashOutStatus { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<bool> IsBeginYear { get; set; }
    
        public virtual Att_LeaveDay Att_LeaveDay { get; set; }
        public virtual Att_Overtime Att_Overtime { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
    }
}
