//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_Roster
    {
        public System.Guid ID { get; set; }
        public System.Guid ProfileID { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> MonShiftID { get; set; }
        public Nullable<System.Guid> MonShift2ID { get; set; }
        public Nullable<System.Guid> TueShiftID { get; set; }
        public Nullable<System.Guid> TueShift2ID { get; set; }
        public Nullable<System.Guid> WedShiftID { get; set; }
        public Nullable<System.Guid> WedShift2ID { get; set; }
        public Nullable<System.Guid> ThuShiftID { get; set; }
        public Nullable<System.Guid> ThuShift2ID { get; set; }
        public Nullable<System.Guid> FriShiftID { get; set; }
        public Nullable<System.Guid> FriShift2ID { get; set; }
        public Nullable<System.Guid> SatShiftID { get; set; }
        public Nullable<System.Guid> SatShift2ID { get; set; }
        public Nullable<System.Guid> SunShiftID { get; set; }
        public Nullable<System.Guid> SunShift2ID { get; set; }
        public Nullable<System.Guid> WorkGroupID { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> ProductionLineID { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
        public Nullable<System.Guid> UserApproveID { get; set; }
        public Nullable<System.Guid> UserApproveID2 { get; set; }
        public string Status { get; set; }
        public string Lable { get; set; }
        public Nullable<System.DateTime> DateApprove { get; set; }
        public Nullable<System.DateTime> DateApprove2 { get; set; }
        public Nullable<bool> IsNotValidContinue { get; set; }
        public Nullable<bool> IsNotValidLimitTime { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> SpecialReasonID { get; set; }
        public string RosterGroupName { get; set; }
    
        public virtual Cat_OrgStructure Cat_OrgStructure { get; set; }
        public virtual Cat_OvertimeReson Cat_OvertimeReson { get; set; }
        public virtual Cat_ProductionLine Cat_ProductionLine { get; set; }
        public virtual Cat_Shift Cat_Shift { get; set; }
        public virtual Cat_Shift Cat_Shift1 { get; set; }
        public virtual Cat_Shift Cat_Shift2 { get; set; }
        public virtual Cat_Shift Cat_Shift3 { get; set; }
        public virtual Cat_Shift Cat_Shift4 { get; set; }
        public virtual Cat_Shift Cat_Shift5 { get; set; }
        public virtual Cat_Shift Cat_Shift6 { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo1 { get; set; }
    }
}
