//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_LeaveDay
    {
        public Att_LeaveDay()
        {
            this.Att_TimeOffInLieu = new HashSet<Att_TimeOffInLieu>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ProfileID { get; set; }
        public System.Guid LeaveDayTypeID { get; set; }
        public Nullable<System.Guid> UserApproveID { get; set; }
        public Nullable<System.Guid> UserApproveID2 { get; set; }
        public Nullable<System.Guid> InsuranceRecordID { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string Status { get; set; }
        public string CommentApprove { get; set; }
        public string Comment { get; set; }
        public string DeclineReason { get; set; }
        public string UserRegister { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public string UserApprove { get; set; }
        public Nullable<System.DateTime> DateApprove { get; set; }
        public double Duration { get; set; }
        public Nullable<double> TotalDuration { get; set; }
        public string DurationType { get; set; }
        public Nullable<System.Guid> RelativesID { get; set; }
        public Nullable<System.Guid> RelativeTypeID { get; set; }
        public string Voucher { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string PayMethod { get; set; }
        public Nullable<bool> IsInvalidIns { get; set; }
        public string LeaveFormNo { get; set; }
        public Nullable<System.Guid> OvertimeID { get; set; }
        public string UserOutSys { get; set; }
        public string SendEmailStatus { get; set; }
        public Nullable<System.Guid> UserRejectID { get; set; }
        public Nullable<System.DateTime> DateReject { get; set; }
        public Nullable<double> LeaveDays { get; set; }
        public Nullable<double> LeaveHours { get; set; }
    
        public virtual Cat_LeaveDayType Cat_LeaveDayType { get; set; }
        public virtual Att_Overtime Att_Overtime { get; set; }
        public virtual Cat_RelativeType Cat_RelativeType { get; set; }
        public virtual Hre_InsuranceRecord Hre_InsuranceRecord { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual Hre_Relatives Hre_Relatives { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo1 { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo2 { get; set; }
        public virtual ICollection<Att_TimeOffInLieu> Att_TimeOffInLieu { get; set; }
    }
}
