//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Can_FoodRegister
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> FoodID { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> ShiftID { get; set; }
        public string ObjectType { get; set; }
        public Nullable<System.Guid> ObjectID { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UserRegister { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public Nullable<System.Guid> UserApprove { get; set; }
        public Nullable<System.DateTime> DateApprove { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> FoodID2 { get; set; }
        public Nullable<System.Guid> MenuID { get; set; }
        public Nullable<System.Guid> MenuID2 { get; set; }
    
        public virtual Can_Food Can_Food { get; set; }
        public virtual Can_Food Can_Food1 { get; set; }
        public virtual Can_Menu Can_Menu { get; set; }
        public virtual Can_Menu Can_Menu1 { get; set; }
        public virtual Cat_Shift Cat_Shift { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo1 { get; set; }
    }
}
