//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Qualification
    {
        public Cat_Qualification()
        {
            this.Hre_Contract = new HashSet<Hre_Contract>();
            this.Hre_ProfileQualification = new HashSet<Hre_ProfileQualification>();
            this.Rec_CandidateQualification = new HashSet<Rec_CandidateQualification>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string QualificationName { get; set; }
        public string Notes { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual ICollection<Hre_Contract> Hre_Contract { get; set; }
        public virtual ICollection<Hre_ProfileQualification> Hre_ProfileQualification { get; set; }
        public virtual ICollection<Rec_CandidateQualification> Rec_CandidateQualification { get; set; }
    }
}
