//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_EntityLabel
    {
        public Cat_EntityLabel()
        {
            this.Sys_GroupLabel = new HashSet<Sys_GroupLabel>();
        }
    
        public System.Guid ID { get; set; }
        public string EntityLabelName { get; set; }
        public string EntityName { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string UserCreate { get; set; }
        public string ServerCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string UserUpdate { get; set; }
        public string ServerUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual ICollection<Sys_GroupLabel> Sys_GroupLabel { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo { get; set; }
    }
}
