//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Province
    {
        public Cat_Province()
        {
            this.Cat_District = new HashSet<Cat_District>();
            this.Cat_Village = new HashSet<Cat_Village>();
            this.Hre_BusinessTrip = new HashSet<Hre_BusinessTrip>();
            this.Hre_Profile = new HashSet<Hre_Profile>();
            this.Hre_Profile1 = new HashSet<Hre_Profile>();
            this.Hre_Profile2 = new HashSet<Hre_Profile>();
            this.Hre_Profile3 = new HashSet<Hre_Profile>();
            this.Hre_Profile4 = new HashSet<Hre_Profile>();
            this.Hre_Profile5 = new HashSet<Hre_Profile>();
            this.Rec_Candidate = new HashSet<Rec_Candidate>();
            this.Rec_Candidate1 = new HashSet<Rec_Candidate>();
            this.Rec_Candidate2 = new HashSet<Rec_Candidate>();
            this.Rec_Candidate3 = new HashSet<Rec_Candidate>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string ProvinceName { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public Nullable<System.Guid> RegionID { get; set; }
        public Nullable<int> Order { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual Cat_Country Cat_Country { get; set; }
        public virtual ICollection<Cat_District> Cat_District { get; set; }
        public virtual Cat_Region Cat_Region { get; set; }
        public virtual ICollection<Cat_Village> Cat_Village { get; set; }
        public virtual ICollection<Hre_BusinessTrip> Hre_BusinessTrip { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile1 { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile2 { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile3 { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile4 { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile5 { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate1 { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate2 { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate3 { get; set; }
    }
}
