//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Position
    {
        public Cat_Position()
        {
            this.Cat_JobTitle = new HashSet<Cat_JobTitle>();
            this.Eva_PerformanceTemplate = new HashSet<Eva_PerformanceTemplate>();
            this.Hre_AppendixContract = new HashSet<Hre_AppendixContract>();
            this.Hre_Contract = new HashSet<Hre_Contract>();
            this.Hre_HistoryProfile = new HashSet<Hre_HistoryProfile>();
            this.Hre_HRPlanItem = new HashSet<Hre_HRPlanItem>();
            this.Hre_Profile = new HashSet<Hre_Profile>();
            this.Hre_ProfilePromotion = new HashSet<Hre_ProfilePromotion>();
            this.Hre_ProfilePromotion1 = new HashSet<Hre_ProfilePromotion>();
            this.Hre_WorkHistory = new HashSet<Hre_WorkHistory>();
            this.Rec_JobVacancy = new HashSet<Rec_JobVacancy>();
            this.Rec_Candidate = new HashSet<Rec_Candidate>();
            this.Rec_JobVacancy1 = new HashSet<Rec_JobVacancy>();
            this.Rec_RecruitmentCampaignItem = new HashSet<Rec_RecruitmentCampaignItem>();
        }
    
        public System.Guid ID { get; set; }
        public string PositionName { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
        public Nullable<System.Guid> CostCentreID { get; set; }
        public Nullable<double> TargetAmount { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string PositionEngName { get; set; }
        public string Description { get; set; }
    
        public virtual Cat_CostCentre Cat_CostCentre { get; set; }
        public virtual ICollection<Cat_JobTitle> Cat_JobTitle { get; set; }
        public virtual Cat_OrgStructure Cat_OrgStructure { get; set; }
        public virtual ICollection<Eva_PerformanceTemplate> Eva_PerformanceTemplate { get; set; }
        public virtual ICollection<Hre_AppendixContract> Hre_AppendixContract { get; set; }
        public virtual ICollection<Hre_Contract> Hre_Contract { get; set; }
        public virtual ICollection<Hre_HistoryProfile> Hre_HistoryProfile { get; set; }
        public virtual ICollection<Hre_HRPlanItem> Hre_HRPlanItem { get; set; }
        public virtual ICollection<Hre_Profile> Hre_Profile { get; set; }
        public virtual ICollection<Hre_ProfilePromotion> Hre_ProfilePromotion { get; set; }
        public virtual ICollection<Hre_ProfilePromotion> Hre_ProfilePromotion1 { get; set; }
        public virtual ICollection<Hre_WorkHistory> Hre_WorkHistory { get; set; }
        public virtual ICollection<Rec_JobVacancy> Rec_JobVacancy { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate { get; set; }
        public virtual ICollection<Rec_JobVacancy> Rec_JobVacancy1 { get; set; }
        public virtual ICollection<Rec_RecruitmentCampaignItem> Rec_RecruitmentCampaignItem { get; set; }
    }
}
