//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Shift
    {
        public Cat_Shift()
        {
            this.Att_AttendanceTableItem = new HashSet<Att_AttendanceTableItem>();
            this.Att_InOut = new HashSet<Att_InOut>();
            this.Att_InOut1 = new HashSet<Att_InOut>();
            this.Att_Overtime = new HashSet<Att_Overtime>();
            this.Att_Roster = new HashSet<Att_Roster>();
            this.Att_Roster1 = new HashSet<Att_Roster>();
            this.Att_Roster2 = new HashSet<Att_Roster>();
            this.Att_Roster3 = new HashSet<Att_Roster>();
            this.Att_Roster4 = new HashSet<Att_Roster>();
            this.Att_Roster5 = new HashSet<Att_Roster>();
            this.Att_Roster6 = new HashSet<Att_Roster>();
            this.Att_RosterGroup = new HashSet<Att_RosterGroup>();
            this.Att_RosterGroup1 = new HashSet<Att_RosterGroup>();
            this.Att_RosterGroup2 = new HashSet<Att_RosterGroup>();
            this.Att_RosterGroup3 = new HashSet<Att_RosterGroup>();
            this.Att_RosterGroup4 = new HashSet<Att_RosterGroup>();
            this.Att_RosterGroup5 = new HashSet<Att_RosterGroup>();
            this.Att_RosterGroup6 = new HashSet<Att_RosterGroup>();
            this.Att_Workday = new HashSet<Att_Workday>();
            this.Att_Workday1 = new HashSet<Att_Workday>();
            this.Att_Workday2 = new HashSet<Att_Workday>();
            this.Can_FoodRegister = new HashSet<Can_FoodRegister>();
            this.Cat_GradeCfg = new HashSet<Cat_GradeCfg>();
            this.Cat_GradeCfg1 = new HashSet<Cat_GradeCfg>();
            this.Cat_GradeCfg2 = new HashSet<Cat_GradeCfg>();
            this.Cat_GradeCfg3 = new HashSet<Cat_GradeCfg>();
            this.Cat_GradeCfg4 = new HashSet<Cat_GradeCfg>();
            this.Cat_GradeCfg5 = new HashSet<Cat_GradeCfg>();
            this.Cat_GradeCfg6 = new HashSet<Cat_GradeCfg>();
            this.Cat_Shift1 = new HashSet<Cat_Shift>();
            this.Cat_Shift11 = new HashSet<Cat_Shift>();
            this.Cat_ShiftItem = new HashSet<Cat_ShiftItem>();
            this.Cat_WorkGroup = new HashSet<Cat_WorkGroup>();
            this.Cat_WorkGroup1 = new HashSet<Cat_WorkGroup>();
            this.Cat_WorkGroup2 = new HashSet<Cat_WorkGroup>();
            this.Cat_WorkGroup3 = new HashSet<Cat_WorkGroup>();
            this.Cat_WorkGroup4 = new HashSet<Cat_WorkGroup>();
            this.Cat_WorkGroup5 = new HashSet<Cat_WorkGroup>();
            this.Cat_WorkGroup6 = new HashSet<Cat_WorkGroup>();
            this.Med_HistoryMedical = new HashSet<Med_HistoryMedical>();
        }
    
        public System.Guid ID { get; set; }
        public string ShiftName { get; set; }
        public string Code { get; set; }
        public System.DateTime InTime { get; set; }
        public double CoOut { get; set; }
        public double CoBreakIn { get; set; }
        public double CoBreakOut { get; set; }
        public double MinIn { get; set; }
        public double MaxOut { get; set; }
        public bool IsNightShift { get; set; }
        public bool IsTemporary { get; set; }
        public Nullable<double> WorkHours { get; set; }
        public string ShiftBreakType { get; set; }
        public Nullable<System.DateTime> NightTimeStart { get; set; }
        public Nullable<System.DateTime> NightTimeEnd { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<bool> IsBreakAsWork { get; set; }
        public Nullable<double> ReduceNightShift { get; set; }
        public Nullable<bool> IsNotApplyWorkHoursReal { get; set; }
        public Nullable<double> HourStartOvertime { get; set; }
        public Nullable<bool> IsDoubleShift { get; set; }
        public Nullable<System.Guid> FirstShiftID { get; set; }
        public Nullable<System.Guid> LastShiftID { get; set; }
    
        public virtual ICollection<Att_AttendanceTableItem> Att_AttendanceTableItem { get; set; }
        public virtual ICollection<Att_InOut> Att_InOut { get; set; }
        public virtual ICollection<Att_InOut> Att_InOut1 { get; set; }
        public virtual ICollection<Att_Overtime> Att_Overtime { get; set; }
        public virtual ICollection<Att_Roster> Att_Roster { get; set; }
        public virtual ICollection<Att_Roster> Att_Roster1 { get; set; }
        public virtual ICollection<Att_Roster> Att_Roster2 { get; set; }
        public virtual ICollection<Att_Roster> Att_Roster3 { get; set; }
        public virtual ICollection<Att_Roster> Att_Roster4 { get; set; }
        public virtual ICollection<Att_Roster> Att_Roster5 { get; set; }
        public virtual ICollection<Att_Roster> Att_Roster6 { get; set; }
        public virtual ICollection<Att_RosterGroup> Att_RosterGroup { get; set; }
        public virtual ICollection<Att_RosterGroup> Att_RosterGroup1 { get; set; }
        public virtual ICollection<Att_RosterGroup> Att_RosterGroup2 { get; set; }
        public virtual ICollection<Att_RosterGroup> Att_RosterGroup3 { get; set; }
        public virtual ICollection<Att_RosterGroup> Att_RosterGroup4 { get; set; }
        public virtual ICollection<Att_RosterGroup> Att_RosterGroup5 { get; set; }
        public virtual ICollection<Att_RosterGroup> Att_RosterGroup6 { get; set; }
        public virtual ICollection<Att_Workday> Att_Workday { get; set; }
        public virtual ICollection<Att_Workday> Att_Workday1 { get; set; }
        public virtual ICollection<Att_Workday> Att_Workday2 { get; set; }
        public virtual ICollection<Can_FoodRegister> Can_FoodRegister { get; set; }
        public virtual ICollection<Cat_GradeCfg> Cat_GradeCfg { get; set; }
        public virtual ICollection<Cat_GradeCfg> Cat_GradeCfg1 { get; set; }
        public virtual ICollection<Cat_GradeCfg> Cat_GradeCfg2 { get; set; }
        public virtual ICollection<Cat_GradeCfg> Cat_GradeCfg3 { get; set; }
        public virtual ICollection<Cat_GradeCfg> Cat_GradeCfg4 { get; set; }
        public virtual ICollection<Cat_GradeCfg> Cat_GradeCfg5 { get; set; }
        public virtual ICollection<Cat_GradeCfg> Cat_GradeCfg6 { get; set; }
        public virtual ICollection<Cat_Shift> Cat_Shift1 { get; set; }
        public virtual Cat_Shift Cat_Shift2 { get; set; }
        public virtual ICollection<Cat_Shift> Cat_Shift11 { get; set; }
        public virtual Cat_Shift Cat_Shift3 { get; set; }
        public virtual ICollection<Cat_ShiftItem> Cat_ShiftItem { get; set; }
        public virtual ICollection<Cat_WorkGroup> Cat_WorkGroup { get; set; }
        public virtual ICollection<Cat_WorkGroup> Cat_WorkGroup1 { get; set; }
        public virtual ICollection<Cat_WorkGroup> Cat_WorkGroup2 { get; set; }
        public virtual ICollection<Cat_WorkGroup> Cat_WorkGroup3 { get; set; }
        public virtual ICollection<Cat_WorkGroup> Cat_WorkGroup4 { get; set; }
        public virtual ICollection<Cat_WorkGroup> Cat_WorkGroup5 { get; set; }
        public virtual ICollection<Cat_WorkGroup> Cat_WorkGroup6 { get; set; }
        public virtual ICollection<Med_HistoryMedical> Med_HistoryMedical { get; set; }
    }
}
