//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_OvertimeReson
    {
        public Cat_OvertimeReson()
        {
            this.Att_Overtime = new HashSet<Att_Overtime>();
            this.Att_Overtime1 = new HashSet<Att_Overtime>();
            this.Att_Roster = new HashSet<Att_Roster>();
        }
    
        public System.Guid ID { get; set; }
        public string OvertimeResonName { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string Type { get; set; }
        public string OvertimeResonNameEng { get; set; }
    
        public virtual ICollection<Att_Overtime> Att_Overtime { get; set; }
        public virtual ICollection<Att_Overtime> Att_Overtime1 { get; set; }
        public virtual ICollection<Att_Roster> Att_Roster { get; set; }
    }
}
