//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Process
    {
        public Cat_Process()
        {
            this.Cat_NonConformingRecord = new HashSet<Cat_NonConformingRecord>();
            this.Tra_Course = new HashSet<Tra_Course>();
        }
    
        public System.Guid ID { get; set; }
        public string ProcessName { get; set; }
        public string UserCreate { get; set; }
        public string ServerCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string UserUpdate { get; set; }
        public string ServerUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Cat_NonConformingRecord> Cat_NonConformingRecord { get; set; }
        public virtual ICollection<Tra_Course> Tra_Course { get; set; }
    }
}
