//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_SalaryRank
    {
        public Cat_SalaryRank()
        {
            this.Hre_AppendixContract = new HashSet<Hre_AppendixContract>();
            this.Hre_Contract = new HashSet<Hre_Contract>();
            this.Sal_BasicSalary = new HashSet<Sal_BasicSalary>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> SalaryClassID { get; set; }
        public Nullable<System.Guid> SalaryClassTypeID { get; set; }
        public string SalaryRankName { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> SalaryStandard { get; set; }
        public Nullable<double> SalaryMin { get; set; }
        public Nullable<double> SalaryMax { get; set; }
        public Nullable<System.DateTime> DateOfEffect { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual Cat_SalaryClass Cat_SalaryClass { get; set; }
        public virtual Cat_SalaryClassType Cat_SalaryClassType { get; set; }
        public virtual ICollection<Hre_AppendixContract> Hre_AppendixContract { get; set; }
        public virtual ICollection<Hre_Contract> Hre_Contract { get; set; }
        public virtual ICollection<Sal_BasicSalary> Sal_BasicSalary { get; set; }
    }
}
