//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hre_FacilityInventory
    {
        public System.Guid ID { get; set; }
        public string FacilityInventoryName { get; set; }
        public string InventoryType { get; set; }
        public string TermAccountant { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public Nullable<System.Guid> FacilityID { get; set; }
        public Nullable<System.Guid> FacilityItemID { get; set; }
        public Nullable<double> QtyHead { get; set; }
        public Nullable<double> QtyIn { get; set; }
        public Nullable<double> QtyOut { get; set; }
        public Nullable<double> QtyAvailable { get; set; }
        public string Description { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string Code { get; set; }
    
        public virtual Cat_Category Cat_Category { get; set; }
        public virtual Hre_Facility Hre_Facility { get; set; }
        public virtual Hre_FacilityItem Hre_FacilityItem { get; set; }
    }
}
