//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hre_WorkHistory
    {
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public System.Guid ProfileID { get; set; }
        public System.DateTime DateEffective { get; set; }
        public Nullable<System.Guid> OrganizationStructureID { get; set; }
        public Nullable<System.Guid> PositionID { get; set; }
        public Nullable<System.Guid> CostCentreID { get; set; }
        public string LaborType { get; set; }
        public Nullable<System.Guid> EmployeeTypeID { get; set; }
        public Nullable<System.Guid> PayrollGroupID { get; set; }
        public string WorkLocation { get; set; }
        public string Supervisor { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> JobTitleID { get; set; }
        public string Status { get; set; }
        public string FileAttach { get; set; }
        public string Note { get; set; }
        public string Description { get; set; }
        public string RequirCondit { get; set; }
        public string Rromotion { get; set; }
        public string ShortTasks { get; set; }
        public string LongTasks { get; set; }
        public string Role { get; set; }
        public Nullable<bool> IsJobTitleMain { get; set; }
        public string DecisionNo { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public string DecisionPersion { get; set; }
        public string LocationCode { get; set; }
        public string OrgOld { get; set; }
        public string PositionOld { get; set; }
        public string LaborTypeOld { get; set; }
        public string CostCentreOld { get; set; }
        public string PayrollGroupOld { get; set; }
        public string WorkLocationOld { get; set; }
        public string LocationCodeOld { get; set; }
        public string JobTitleOld { get; set; }
        public string EmployeeTypeOld { get; set; }
        public string SupervisorOld { get; set; }
        public string CodeOld { get; set; }
        public Nullable<System.Guid> OrgLineDefaultID { get; set; }
        public Nullable<System.Guid> ProducteLineDefaultID { get; set; }
        public string FormType { get; set; }
        public string CodeEmp { get; set; }
        public Nullable<bool> IsExistentConcurrentPosition { get; set; }
        public string PositionType { get; set; }
        public Nullable<double> PositionRate { get; set; }
    
        public virtual Cat_CostCentre Cat_CostCentre { get; set; }
        public virtual Cat_EmployeeType Cat_EmployeeType { get; set; }
        public virtual Cat_JobTitle Cat_JobTitle { get; set; }
        public virtual Cat_OrgStructure Cat_OrgStructure { get; set; }
        public virtual Cat_OrgStructure Cat_OrgStructure1 { get; set; }
        public virtual Cat_PayrollGroup Cat_PayrollGroup { get; set; }
        public virtual Cat_Position Cat_Position { get; set; }
        public virtual Cat_ProductionLine Cat_ProductionLine { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
    }
}
