//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hre_BusinessTripCosting
    {
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string BusinessTripCostingName { get; set; }
        public System.Guid BusinessTripID { get; set; }
        public double CostRequire { get; set; }
        public Nullable<System.Guid> CurrencyRequireID { get; set; }
        public double CostApproved { get; set; }
        public Nullable<System.Guid> CurrencyApprovedID { get; set; }
        public double CostPay { get; set; }
        public Nullable<System.Guid> CurrencyPayID { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual Cat_Currency Cat_Currency { get; set; }
        public virtual Cat_Currency Cat_Currency1 { get; set; }
        public virtual Cat_Currency Cat_Currency2 { get; set; }
        public virtual Hre_BusinessTrip Hre_BusinessTrip { get; set; }
    }
}
