//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hre_Facility
    {
        public Hre_Facility()
        {
            this.Hre_FacilityInventory = new HashSet<Hre_FacilityInventory>();
            this.Hre_FacilityIssue = new HashSet<Hre_FacilityIssue>();
            this.Hre_FacilityItem = new HashSet<Hre_FacilityItem>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string FacilityName { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public string Notes { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual Cat_Category Cat_Category { get; set; }
        public virtual ICollection<Hre_FacilityInventory> Hre_FacilityInventory { get; set; }
        public virtual ICollection<Hre_FacilityIssue> Hre_FacilityIssue { get; set; }
        public virtual ICollection<Hre_FacilityItem> Hre_FacilityItem { get; set; }
    }
}
