//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_Disease
    {
        public Med_Disease()
        {
            this.Med_Epidemic = new HashSet<Med_Epidemic>();
            this.Med_HistoryMedical = new HashSet<Med_HistoryMedical>();
            this.Med_Patient = new HashSet<Med_Patient>();
            this.Med_Vaccination = new HashSet<Med_Vaccination>();
        }
    
        public System.Guid ID { get; set; }
        public string DiseaseName { get; set; }
        public string Description { get; set; }
        public string IPUpdate { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Med_Epidemic> Med_Epidemic { get; set; }
        public virtual ICollection<Med_HistoryMedical> Med_HistoryMedical { get; set; }
        public virtual ICollection<Med_Patient> Med_Patient { get; set; }
        public virtual ICollection<Med_Vaccination> Med_Vaccination { get; set; }
    }
}
