//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_AnnualHealth
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BloodPressure { get; set; }
        public string Circulation { get; set; }
        public string Respiratory { get; set; }
        public string Digest { get; set; }
        public string Kidney { get; set; }
        public string Nerve { get; set; }
        public string Result { get; set; }
        public string Description { get; set; }
        public string IPUpdate { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string XRay { get; set; }
        public string Testing { get; set; }
        public string Eye { get; set; }
        public string Oral { get; set; }
        public string Otorhinolaryngology { get; set; }
        public string Supersonic { get; set; }
        public string UrinaryAnalysis { get; set; }
        public string BloodGlucose { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> LineId { get; set; }
        public string Mental { get; set; }
        public string MotionSystem { get; set; }
        public string SkinDisease { get; set; }
        public string Endocrinology { get; set; }
        public string CTM { get; set; }
        public string BloodType { get; set; }
        public string HBsAg { get; set; }
        public string BreastSuperSonic { get; set; }
        public string AntiHBs { get; set; }
        public string XRayHeart { get; set; }
        public string LipidBlood { get; set; }
        public string MeasuringMuscle { get; set; }
        public string XRayVeinFoot { get; set; }
        public string HPylori { get; set; }
        public string HIV { get; set; }
        public string LiverEnzymes { get; set; }
        public string CLSOrther { get; set; }
        public string TMH { get; set; }
        public Nullable<System.Guid> TypeResultHealthID { get; set; }
        public string QuickStick { get; set; }
        public Nullable<int> CheckHealthTimes { get; set; }
        public Nullable<double> NumberSerial { get; set; }
    
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual Med_TypeResultHealth Med_TypeResultHealth { get; set; }
    }
}
