//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rec_JobVacancy
    {
        public Rec_JobVacancy()
        {
            this.Rec_Candidate = new HashSet<Rec_Candidate>();
            this.Rec_QuestionaireJobVacancy = new HashSet<Rec_QuestionaireJobVacancy>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string JobVacancyName { get; set; }
        public System.Guid PositionID { get; set; }
        public Nullable<System.Guid> UserApproveID { get; set; }
        public Nullable<System.Guid> DeptInChargeID { get; set; }
        public Nullable<double> SalaryMax { get; set; }
        public Nullable<double> SalaryMin { get; set; }
        public string FileAttachment { get; set; }
        public Nullable<System.Guid> RecruitmentCampaignID { get; set; }
        public string JobDescription { get; set; }
        public string Workplace { get; set; }
        public string Requirement { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
        public string SourceAds { get; set; }
        public string JobLevel { get; set; }
        public string PayrollNumber { get; set; }
        public Nullable<int> TotalEmpPosition { get; set; }
        public string EmpNameReplace { get; set; }
        public string PositionReplace { get; set; }
        public Nullable<System.Guid> ReasonsForReplacementID { get; set; }
        public string JobLevelReplace { get; set; }
        public Nullable<System.DateTime> DateProposal { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateComplete { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DatePublish { get; set; }
        public Nullable<bool> IsExternal { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<bool> IsFirstApprove { get; set; }
        public Nullable<bool> IsRevaluation { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string LastStatus { get; set; }
        public string UserApprove { get; set; }
        public string UserApprove1 { get; set; }
        public Nullable<System.DateTime> DateApprove { get; set; }
        public Nullable<System.DateTime> DateApprove1 { get; set; }
        public bool IsBelongToPlan { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string UserSubmit { get; set; }
        public Nullable<System.DateTime> DateSubmit { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public Nullable<System.Guid> JobTitleID { get; set; }
        public Nullable<int> FemaleRequestedNo { get; set; }
        public Nullable<System.Guid> UserAssingID { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> DateStartApprove { get; set; }
        public Nullable<System.DateTime> DateEndApprove { get; set; }
        public Nullable<double> ValueApprove { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<System.Guid> SourceAdsID { get; set; }
        public Nullable<System.Guid> PositionReplaceID { get; set; }
        public string SalaryPayment { get; set; }
        public string Notes { get; set; }
        public string ApproveHistory { get; set; }
    
        public virtual Cat_JobTitle Cat_JobTitle { get; set; }
        public virtual Cat_NameEntity Cat_NameEntity { get; set; }
        public virtual Cat_OrgStructure Cat_OrgStructure { get; set; }
        public virtual Cat_OrgStructure Cat_OrgStructure1 { get; set; }
        public virtual Cat_Position Cat_Position { get; set; }
        public virtual Cat_Position Cat_Position1 { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate { get; set; }
        public virtual Rec_RecruitmentCampaign Rec_RecruitmentCampaign { get; set; }
        public virtual Rec_SourceAds Rec_SourceAds { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo1 { get; set; }
        public virtual ICollection<Rec_QuestionaireJobVacancy> Rec_QuestionaireJobVacancy { get; set; }
    }
}
