//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rec_Interview
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> QuestionQuestionaireID { get; set; }
        public string Code { get; set; }
        public string InterviewName { get; set; }
        public Nullable<System.DateTime> DateInterview { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> CandidateID { get; set; }
        public Nullable<System.Guid> InterviewCompaignID { get; set; }
        public string Interviewer1 { get; set; }
        public string Interviewer2 { get; set; }
        public Nullable<System.Guid> ProfileID1 { get; set; }
        public Nullable<System.Guid> ProfileID2 { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public Nullable<double> Score1 { get; set; }
        public Nullable<double> Score2 { get; set; }
        public Nullable<double> Score { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public Nullable<System.Guid> UserApproveID { get; set; }
        public string Hour { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
        public string Description { get; set; }
        public string FileAttachment { get; set; }
    
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual Hre_Profile Hre_Profile1 { get; set; }
        public virtual Rec_Candidate Rec_Candidate { get; set; }
        public virtual Rec_InterviewCampaign Rec_InterviewCampaign { get; set; }
        public virtual Rec_Questionaire Rec_Questionaire { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo { get; set; }
    }
}
