//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rec_Questionaire
    {
        public Rec_Questionaire()
        {
            this.Rec_Interview = new HashSet<Rec_Interview>();
            this.Rec_Question = new HashSet<Rec_Question>();
            this.Rec_QuestionaireJobVacancy = new HashSet<Rec_QuestionaireJobVacancy>();
            this.Rec_Response = new HashSet<Rec_Response>();
        }
    
        public System.Guid ID { get; set; }
        public string QuestionaireName { get; set; }
        public string Status { get; set; }
        public string Code { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string Module { get; set; }
    
        public virtual ICollection<Rec_Interview> Rec_Interview { get; set; }
        public virtual ICollection<Rec_Question> Rec_Question { get; set; }
        public virtual ICollection<Rec_QuestionaireJobVacancy> Rec_QuestionaireJobVacancy { get; set; }
        public virtual ICollection<Rec_Response> Rec_Response { get; set; }
    }
}
