//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_SalaryInformation
    {
        public System.Guid ID { get; set; }
        public System.Guid ProfileID { get; set; }
        public string AccountNo { get; set; }
        public Nullable<System.Guid> BankID { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string AccountName2 { get; set; }
        public string AccountNo2 { get; set; }
        public string SwiftCode2 { get; set; }
        public string SortCode2 { get; set; }
        public string AmountTransfer2 { get; set; }
        public Nullable<System.Guid> BankID2 { get; set; }
        public string AccountName { get; set; }
        public string SwiftCode { get; set; }
        public string SortCode { get; set; }
        public string AmountTransfer { get; set; }
        public Nullable<System.Guid> CurrencyID { get; set; }
        public Nullable<System.Guid> CurrencyID2 { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsDefault2 { get; set; }
        public string BankNameCustomer { get; set; }
        public string BankNameCustomer2 { get; set; }
        public Nullable<System.Guid> AccountCurrencyID { get; set; }
        public Nullable<System.Guid> AccountCurrencyID2 { get; set; }
        public Nullable<bool> IsCash { get; set; }
        public Nullable<bool> IsCash2 { get; set; }
        public string BankBrandName { get; set; }
        public string BankBrandName2 { get; set; }
    
        public virtual Cat_Bank Cat_Bank { get; set; }
        public virtual Cat_Bank Cat_Bank1 { get; set; }
        public virtual Cat_Currency Cat_Currency { get; set; }
        public virtual Cat_Currency Cat_Currency1 { get; set; }
        public virtual Cat_Currency Cat_Currency2 { get; set; }
        public virtual Cat_Currency Cat_Currency3 { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
    }
}
