//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_UnusualAllowance
    {
        public System.Guid ID { get; set; }
        public System.Guid ProfileID { get; set; }
        public System.Guid UnusualEDTypeID { get; set; }
        public Nullable<System.Guid> BudgetId { get; set; }
        public string Type { get; set; }
        public double Amount { get; set; }
        public System.Guid CurrencyID { get; set; }
        public System.DateTime MonthStart { get; set; }
        public System.DateTime MonthEnd { get; set; }
        public bool AddToHourlyRate { get; set; }
        public bool ChargePIT { get; set; }
        public string Notes { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<bool> IsFollowDay { get; set; }
    
        public virtual Cat_Budget Cat_Budget { get; set; }
        public virtual Cat_Currency Cat_Currency { get; set; }
        public virtual Cat_UnusualAllowanceCfg Cat_UnusualAllowanceCfg { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
    }
}
