//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_PayrollTable
    {
        public Sal_PayrollTable()
        {
            this.Sal_PayrollTableItem = new HashSet<Sal_PayrollTableItem>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ProfileID { get; set; }
        public System.DateTime MonthYear { get; set; }
        public Nullable<System.Guid> CutOffDurationID { get; set; }
        public string Status { get; set; }
        public Nullable<double> BasicSalary { get; set; }
        public Nullable<double> GrossSalary { get; set; }
        public Nullable<double> HourlyRate { get; set; }
        public Nullable<double> PayableWorkDays { get; set; }
        public Nullable<double> WorkingSalary { get; set; }
        public Nullable<double> OvertimeSalary { get; set; }
        public Nullable<double> Allowance { get; set; }
        public Nullable<double> Deduction { get; set; }
        public Nullable<double> OtherEarning { get; set; }
        public Nullable<double> OtherDeduction { get; set; }
        public Nullable<double> AmountInsUnemployCom { get; set; }
        public Nullable<double> AmountInsUnemployEmp { get; set; }
        public Nullable<double> AmountInsHealthCom { get; set; }
        public Nullable<double> AmountInsHealthEmp { get; set; }
        public Nullable<double> AmountInsSocialCom { get; set; }
        public Nullable<double> AmountInsSocialEmp { get; set; }
        public double IncomeBeforeTax { get; set; }
        public int DependantCount { get; set; }
        public double IncomeTaxable { get; set; }
        public double AmountPaidPITEmp { get; set; }
        public double AmountPaidPITCom { get; set; }
        public double IncomeNET { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
        public Nullable<System.Guid> PositionID { get; set; }
        public Nullable<System.Guid> JobTitleID { get; set; }
        public Nullable<System.Guid> EmployeeTypeID { get; set; }
        public Nullable<System.Guid> PayrollGroupID { get; set; }
        public Nullable<System.Guid> CostCentreID { get; set; }
    
        public virtual Att_CutOffDuration Att_CutOffDuration { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual ICollection<Sal_PayrollTableItem> Sal_PayrollTableItem { get; set; }
    }
}
