//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal_SalaryDepartment
    {
        public Sal_SalaryDepartment()
        {
            this.Sal_SalaryDepartmentItem = new HashSet<Sal_SalaryDepartmentItem>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CutOffDurationID { get; set; }
        public System.DateTime MonthYear { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string TypeCompute { get; set; }
        public Nullable<System.Guid> ProductionLineID { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
        public double Amount { get; set; }
        public Nullable<double> TotalGroupHours { get; set; }
        public Nullable<System.Guid> CurrencyID { get; set; }
        public Nullable<bool> IsAll { get; set; }
        public string Note { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual Att_CutOffDuration Att_CutOffDuration { get; set; }
        public virtual Cat_Currency Cat_Currency { get; set; }
        public virtual Cat_OrgStructure Cat_OrgStructure { get; set; }
        public virtual Cat_ProductionLine Cat_ProductionLine { get; set; }
        public virtual ICollection<Sal_SalaryDepartmentItem> Sal_SalaryDepartmentItem { get; set; }
    }
}
