//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_UserInfo
    {
        public Sys_UserInfo()
        {
            this.Att_LeaveDay = new HashSet<Att_LeaveDay>();
            this.Att_LeaveDay1 = new HashSet<Att_LeaveDay>();
            this.Att_LeaveDay2 = new HashSet<Att_LeaveDay>();
            this.Att_Overtime = new HashSet<Att_Overtime>();
            this.Att_Overtime1 = new HashSet<Att_Overtime>();
            this.Att_Overtime2 = new HashSet<Att_Overtime>();
            this.Att_Roster = new HashSet<Att_Roster>();
            this.Att_Roster1 = new HashSet<Att_Roster>();
            this.Att_RosterGroup = new HashSet<Att_RosterGroup>();
            this.Att_RosterGroup1 = new HashSet<Att_RosterGroup>();
            this.Can_FoodRegister = new HashSet<Can_FoodRegister>();
            this.Can_FoodRegister1 = new HashSet<Can_FoodRegister>();
            this.Cat_EntityLabel = new HashSet<Cat_EntityLabel>();
            this.Hre_BusinessTrip = new HashSet<Hre_BusinessTrip>();
            this.Hre_BusinessTrip1 = new HashSet<Hre_BusinessTrip>();
            this.Hre_FacilityIssue = new HashSet<Hre_FacilityIssue>();
            this.Hre_FacilityIssue1 = new HashSet<Hre_FacilityIssue>();
            this.Hre_FacilityIssue2 = new HashSet<Hre_FacilityIssue>();
            this.Hre_FacilityItem = new HashSet<Hre_FacilityItem>();
            this.Hre_FacilityItem1 = new HashSet<Hre_FacilityItem>();
            this.Hre_Reward = new HashSet<Hre_Reward>();
            this.Ins_LeaveDayIns = new HashSet<Ins_LeaveDayIns>();
            this.Ins_LeaveDayIns1 = new HashSet<Ins_LeaveDayIns>();
            this.Rec_Candidate = new HashSet<Rec_Candidate>();
            this.Rec_Interview = new HashSet<Rec_Interview>();
            this.Rec_JobVacancy = new HashSet<Rec_JobVacancy>();
            this.Rec_JobVacancy1 = new HashSet<Rec_JobVacancy>();
            this.Sal_UnusualPay = new HashSet<Sal_UnusualPay>();
            this.Sal_UnusualPay1 = new HashSet<Sal_UnusualPay>();
            this.Sys_ChangedObject = new HashSet<Sys_ChangedObject>();
            this.Sys_CodeObjectByUserNDate = new HashSet<Sys_CodeObjectByUserNDate>();
            this.Sys_ColumnMode = new HashSet<Sys_ColumnMode>();
            this.Sys_LayOut = new HashSet<Sys_LayOut>();
            this.Sys_LockObject = new HashSet<Sys_LockObject>();
            this.Sys_LockObject1 = new HashSet<Sys_LockObject>();
            this.Sys_UserApprove = new HashSet<Sys_UserApprove>();
            this.Sys_UserDataGroup = new HashSet<Sys_UserDataGroup>();
            this.Sys_UserGroup = new HashSet<Sys_UserGroup>();
            this.Sys_UsingUser = new HashSet<Sys_UsingUser>();
            this.Tra_RequirementTrain = new HashSet<Tra_RequirementTrain>();
            this.Tra_RequirementTrain1 = new HashSet<Tra_RequirementTrain>();
            this.Tra_RequirementTrain2 = new HashSet<Tra_RequirementTrain>();
            this.Tra_RequirementTrainingApprove = new HashSet<Tra_RequirementTrainingApprove>();
        }
    
        public System.Guid ID { get; set; }
        public string UserInfoName { get; set; }
        public string UserLogin { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
        public Nullable<System.Guid> ProfileID { get; set; }
        public bool IsActivate { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> UserGroupID { get; set; }
        public Nullable<System.Guid> SurveyID { get; set; }
        public string UserType { get; set; }
        public Nullable<System.DateTime> DateChangePasssword { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> DatePasswordExpired { get; set; }
        public string Code { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<bool> IsCheckLDAP { get; set; }
    
        public virtual ICollection<Att_LeaveDay> Att_LeaveDay { get; set; }
        public virtual ICollection<Att_LeaveDay> Att_LeaveDay1 { get; set; }
        public virtual ICollection<Att_LeaveDay> Att_LeaveDay2 { get; set; }
        public virtual ICollection<Att_Overtime> Att_Overtime { get; set; }
        public virtual ICollection<Att_Overtime> Att_Overtime1 { get; set; }
        public virtual ICollection<Att_Overtime> Att_Overtime2 { get; set; }
        public virtual ICollection<Att_Roster> Att_Roster { get; set; }
        public virtual ICollection<Att_Roster> Att_Roster1 { get; set; }
        public virtual ICollection<Att_RosterGroup> Att_RosterGroup { get; set; }
        public virtual ICollection<Att_RosterGroup> Att_RosterGroup1 { get; set; }
        public virtual ICollection<Can_FoodRegister> Can_FoodRegister { get; set; }
        public virtual ICollection<Can_FoodRegister> Can_FoodRegister1 { get; set; }
        public virtual ICollection<Cat_EntityLabel> Cat_EntityLabel { get; set; }
        public virtual Cat_OrgStructure Cat_OrgStructure { get; set; }
        public virtual ICollection<Hre_BusinessTrip> Hre_BusinessTrip { get; set; }
        public virtual ICollection<Hre_BusinessTrip> Hre_BusinessTrip1 { get; set; }
        public virtual ICollection<Hre_FacilityIssue> Hre_FacilityIssue { get; set; }
        public virtual ICollection<Hre_FacilityIssue> Hre_FacilityIssue1 { get; set; }
        public virtual ICollection<Hre_FacilityIssue> Hre_FacilityIssue2 { get; set; }
        public virtual ICollection<Hre_FacilityItem> Hre_FacilityItem { get; set; }
        public virtual ICollection<Hre_FacilityItem> Hre_FacilityItem1 { get; set; }
        public virtual ICollection<Hre_Reward> Hre_Reward { get; set; }
        public virtual ICollection<Ins_LeaveDayIns> Ins_LeaveDayIns { get; set; }
        public virtual ICollection<Ins_LeaveDayIns> Ins_LeaveDayIns1 { get; set; }
        public virtual ICollection<Rec_Candidate> Rec_Candidate { get; set; }
        public virtual ICollection<Rec_Interview> Rec_Interview { get; set; }
        public virtual ICollection<Rec_JobVacancy> Rec_JobVacancy { get; set; }
        public virtual ICollection<Rec_JobVacancy> Rec_JobVacancy1 { get; set; }
        public virtual ICollection<Sal_UnusualPay> Sal_UnusualPay { get; set; }
        public virtual ICollection<Sal_UnusualPay> Sal_UnusualPay1 { get; set; }
        public virtual ICollection<Sys_ChangedObject> Sys_ChangedObject { get; set; }
        public virtual ICollection<Sys_CodeObjectByUserNDate> Sys_CodeObjectByUserNDate { get; set; }
        public virtual ICollection<Sys_ColumnMode> Sys_ColumnMode { get; set; }
        public virtual ICollection<Sys_LayOut> Sys_LayOut { get; set; }
        public virtual ICollection<Sys_LockObject> Sys_LockObject { get; set; }
        public virtual ICollection<Sys_LockObject> Sys_LockObject1 { get; set; }
        public virtual ICollection<Sys_UserApprove> Sys_UserApprove { get; set; }
        public virtual ICollection<Sys_UserDataGroup> Sys_UserDataGroup { get; set; }
        public virtual ICollection<Sys_UserGroup> Sys_UserGroup { get; set; }
        public virtual ICollection<Sys_UsingUser> Sys_UsingUser { get; set; }
        public virtual ICollection<Tra_RequirementTrain> Tra_RequirementTrain { get; set; }
        public virtual ICollection<Tra_RequirementTrain> Tra_RequirementTrain1 { get; set; }
        public virtual ICollection<Tra_RequirementTrain> Tra_RequirementTrain2 { get; set; }
        public virtual ICollection<Tra_RequirementTrainingApprove> Tra_RequirementTrainingApprove { get; set; }
    }
}
