//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tra_Certificate
    {
        public Tra_Certificate()
        {
            this.Cat_Topic = new HashSet<Cat_Topic>();
            this.Cat_TrainLevel = new HashSet<Cat_TrainLevel>();
            this.Hre_ProfileCertificate = new HashSet<Hre_ProfileCertificate>();
            this.Tra_Class = new HashSet<Tra_Class>();
            this.Tra_Trainee = new HashSet<Tra_Trainee>();
            this.Tra_TraineeCertificate = new HashSet<Tra_TraineeCertificate>();
        }
    
        public System.Guid ID { get; set; }
        public string CertificateName { get; set; }
        public string Code { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string Place { get; set; }
        public Nullable<System.Guid> CourseID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Cat_Topic> Cat_Topic { get; set; }
        public virtual ICollection<Cat_TrainLevel> Cat_TrainLevel { get; set; }
        public virtual ICollection<Hre_ProfileCertificate> Hre_ProfileCertificate { get; set; }
        public virtual Tra_Course Tra_Course { get; set; }
        public virtual ICollection<Tra_Class> Tra_Class { get; set; }
        public virtual ICollection<Tra_Trainee> Tra_Trainee { get; set; }
        public virtual ICollection<Tra_TraineeCertificate> Tra_TraineeCertificate { get; set; }
    }
}
