//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tra_Trainee
    {
        public Tra_Trainee()
        {
            this.Cat_NonConformingRecord = new HashSet<Cat_NonConformingRecord>();
            this.Hre_ProfileCertificate = new HashSet<Hre_ProfileCertificate>();
            this.Tra_TraineeCertificate = new HashSet<Tra_TraineeCertificate>();
            this.Tra_TraineeTopic = new HashSet<Tra_TraineeTopic>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ProfileID { get; set; }
        public System.Guid ClassID { get; set; }
        public string Status { get; set; }
        public Nullable<double> Result { get; set; }
        public Nullable<System.Guid> CertificateID { get; set; }
        public string TeacherComment { get; set; }
        public string ProfileComment { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
        public string PracticeMath { get; set; }
        public string TheoreticalMath { get; set; }
        public string AttendanceMath { get; set; }
        public Nullable<double> CostCenter { get; set; }
        public Nullable<double> CostCenterCompanyPay { get; set; }
        public Nullable<System.DateTime> DateExpirationCertificate { get; set; }
        public Nullable<System.DateTime> CertificateDate { get; set; }
        public Nullable<System.DateTime> CommitmentTimeWork { get; set; }
        public string CommitmentOther { get; set; }
        public Nullable<System.Guid> TrainLevelID { get; set; }
        public Nullable<System.DateTime> DatePrintCard { get; set; }
        public string UserPrintCard { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public Nullable<System.DateTime> DateEndRequest { get; set; }
        public Nullable<bool> IsObsolete { get; set; }
        public string RankingName { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.Guid> ReasonID { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> IsCreateFromNewCertificate { get; set; }
        public Nullable<System.Guid> RankingID { get; set; }
        public string ResultXML { get; set; }
    
        public virtual ICollection<Cat_NonConformingRecord> Cat_NonConformingRecord { get; set; }
        public virtual Cat_TrainLevel Cat_TrainLevel { get; set; }
        public virtual Hre_Profile Hre_Profile { get; set; }
        public virtual ICollection<Hre_ProfileCertificate> Hre_ProfileCertificate { get; set; }
        public virtual Tra_Certificate Tra_Certificate { get; set; }
        public virtual Tra_Class Tra_Class { get; set; }
        public virtual Tra_Ranking Tra_Ranking { get; set; }
        public virtual Tra_Reason Tra_Reason { get; set; }
        public virtual ICollection<Tra_TraineeCertificate> Tra_TraineeCertificate { get; set; }
        public virtual ICollection<Tra_TraineeTopic> Tra_TraineeTopic { get; set; }
    }
}
