//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tra_TraineeScore
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TraineeTopicID { get; set; }
        public Nullable<System.Guid> ScoreTypeID { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<double> TheoryScores { get; set; }
        public Nullable<double> PracticeScores { get; set; }
        public Nullable<double> AttendanceScores { get; set; }
        public string Type { get; set; }
        public Nullable<int> Times { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
    
        public virtual Tra_TraineeTopic Tra_TraineeTopic { get; set; }
    }
}
