//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tra_RequirementTrain
    {
        public Tra_RequirementTrain()
        {
            this.Tra_RequirementTrainDetail = new HashSet<Tra_RequirementTrainDetail>();
            this.Tra_RequirementTrainingApprove = new HashSet<Tra_RequirementTrainingApprove>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PlanID { get; set; }
        public Nullable<System.Guid> TopicID { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<System.Guid> UserApproveID { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string RequirementTrainName { get; set; }
        public Nullable<System.Guid> CourseID { get; set; }
        public Nullable<System.DateTime> DateApprove { get; set; }
        public string ApproveXML { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> TrainCategoryID { get; set; }
        public string Target { get; set; }
        public string ResultAchieved { get; set; }
        public string CreatedPosition { get; set; }
        public Nullable<System.Guid> UserApproveID2 { get; set; }
        public Nullable<System.DateTime> DateApprove2 { get; set; }
        public string CommentApprove2 { get; set; }
        public Nullable<System.Guid> UserApproveID3 { get; set; }
        public Nullable<System.DateTime> DateApprove3 { get; set; }
        public string CommentApprove3 { get; set; }
        public Nullable<bool> IsTrainingOutside { get; set; }
        public string TrainingDeptIdea { get; set; }
        public string ManagementDeptIdea { get; set; }
        public string StatusApprove { get; set; }
        public string StatusApprove2 { get; set; }
        public string StatusApprove3 { get; set; }
        public string PersonRequirement { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
    
        public virtual Cat_Topic Cat_Topic { get; set; }
        public virtual Cat_TrainCategory Cat_TrainCategory { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo1 { get; set; }
        public virtual Sys_UserInfo Sys_UserInfo2 { get; set; }
        public virtual Tra_Course Tra_Course { get; set; }
        public virtual Tra_Plan Tra_Plan { get; set; }
        public virtual ICollection<Tra_RequirementTrainDetail> Tra_RequirementTrainDetail { get; set; }
        public virtual ICollection<Tra_RequirementTrainingApprove> Tra_RequirementTrainingApprove { get; set; }
    }
}
