//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Presentation.Hrm7.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tra_Course
    {
        public Tra_Course()
        {
            this.Cat_Topic = new HashSet<Cat_Topic>();
            this.Hre_ProfileCertificate = new HashSet<Hre_ProfileCertificate>();
            this.Tra_Certificate = new HashSet<Tra_Certificate>();
            this.Tra_Class = new HashSet<Tra_Class>();
            this.Tra_CourseTopic = new HashSet<Tra_CourseTopic>();
            this.Tra_RequirementTrain = new HashSet<Tra_RequirementTrain>();
            this.Tra_RequirementTrainDetail = new HashSet<Tra_RequirementTrainDetail>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TrainCategoryID { get; set; }
        public string CourseName { get; set; }
        public string Code { get; set; }
        public string SchoolFee { get; set; }
        public string Category { get; set; }
        public Nullable<bool> IsExternal { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public string TrainningPlace { get; set; }
        public Nullable<System.Guid> ProductionLineID { get; set; }
        public Nullable<System.Guid> ProcessID { get; set; }
        public string StandardTheory { get; set; }
        public string StandardPractice { get; set; }
        public string StandardAttendance { get; set; }
        public Nullable<System.Guid> RankingGroupID { get; set; }
        public Nullable<bool> IsComplex { get; set; }
        public Nullable<double> MinimumScore { get; set; }
        public Nullable<double> MaximumScore { get; set; }
        public string Formula { get; set; }
        public string TypeHandleFomular { get; set; }
        public Nullable<bool> IsAutoCreated { get; set; }
        public string Description { get; set; }
    
        public virtual Cat_Process Cat_Process { get; set; }
        public virtual Cat_ProductionLine Cat_ProductionLine { get; set; }
        public virtual ICollection<Cat_Topic> Cat_Topic { get; set; }
        public virtual Cat_TrainCategory Cat_TrainCategory { get; set; }
        public virtual ICollection<Hre_ProfileCertificate> Hre_ProfileCertificate { get; set; }
        public virtual ICollection<Tra_Certificate> Tra_Certificate { get; set; }
        public virtual ICollection<Tra_Class> Tra_Class { get; set; }
        public virtual Tra_RankingGroup Tra_RankingGroup { get; set; }
        public virtual ICollection<Tra_CourseTopic> Tra_CourseTopic { get; set; }
        public virtual ICollection<Tra_RequirementTrain> Tra_RequirementTrain { get; set; }
        public virtual ICollection<Tra_RequirementTrainDetail> Tra_RequirementTrainDetail { get; set; }
    }
}
