using System;

namespace HRM.Business.Recruitment.Models
{
    public class Rec_RecruitmentHistoryEntity : HRM.Business.BaseModel.HRMBaseModel
    {
        public Nullable<int> CandidateNumber { get; set; }
        public System.Guid CandidateID { get; set; }
        public Guid? SalaryClassID { get; set; }
        public string CurrencyName3 { get; set; }
        public string CurrencyName1 { get; set; }
        public Nullable<bool> PassFilterResume { get; set; }
        public string CurrencyName2 { get; set; }
        public string CurrencyName { get; set; }
        public double? SalaryApproveMoney { get; set; }
        public double? SalaryCurrentMoney { get; set; }
        public double? SalarySuggestMoney { get; set; }
        public Nullable<System.Guid> SourceAdsID { get; set; }
        public string CandidateName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string IdentifyNumber { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> DateIssuePassport { get; set; }
        public Nullable<System.DateTime> DateExpiresPassport { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Eyesight { get; set; }
        public string TimeWorkType { get; set; }
        public Nullable<bool> IsAcceptOvertime { get; set; }
        public string PeopleGuarantee { get; set; }
        public string PositionGuarantee { get; set; }
        public string Vehicles { get; set; }
        public string TAddress { get; set; }
        public string SourceAds { get; set; }
        public string HealthStatus { get; set; }
        public Nullable<System.Guid> EthnicID { get; set; }
        public Nullable<System.Guid> ReligionID { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<System.Guid> MarriageStatusID { get; set; }
        public Nullable<System.Guid> UserWaitApproveID { get; set; }
        public Nullable<System.DateTime> DateApprove { get; set; }
        public string PersonalPlan { get; set; }
        public string PersionalWebsite { get; set; }
        public string PersonalTarget { get; set; }
        public string SpecialSkill { get; set; }
        public string OrientationCareer { get; set; }
        public string LongtermOrientation { get; set; }
        public string ShorttermOrientation { get; set; }
        public string MemberOfAssociation { get; set; }
        public string WorkplaceSuggestion { get; set; }
        public string Status { get; set; }
        public string StatusLast { get; set; }
        public Nullable<System.DateTime> DateApply { get; set; }
        public Nullable<System.DateTime> DateStartWorking { get; set; }
        public string WorkingType { get; set; }
        public string WorkingTypePeriod { get; set; }
        public string Assessment { get; set; }
        public Nullable<double> ScorePotential { get; set; }
        public Nullable<System.Guid> RecruitmentCampaignID { get; set; }
        public Nullable<System.Guid> OrgStructureID { get; set; }
        public Nullable<System.Guid> JobVacancyID { get; set; }
        public Nullable<System.Guid> TagID { get; set; }
        public Nullable<System.Guid> PositionID { get; set; }
        public string PositionName { get; set; }
        public string OrgStructureName { get; set; }
        public string Description { get; set; }
        public string SalarySuggest { get; set; }
        public string SalaryApprove { get; set; }
        public string SalaryCurrent { get; set; }
        public Nullable<System.Guid> CurrencyID { get; set; }
        public string Weak { get; set; }
        public string Strong { get; set; }
        public Nullable<bool> IsReadyBizTrip { get; set; }
        public double YearOfExperience { get; set; }
        public Nullable<bool> IsAnnounceResult { get; set; }
        public string AssociationProfessional { get; set; }
        public string IntroducePerson { get; set; }
        public string FileAttachment { get; set; }
        public string ApproveHistory { get; set; }
        public string ServerUpdate { get; set; }
        public string ServerCreate { get; set; }
        public string UserUpdate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserLockID { get; set; }
        public Nullable<System.DateTime> DateLock { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IPCreate { get; set; }
        public string IPUpdate { get; set; }
        public Nullable<System.Guid> RecSourceID { get; set; }
        public Nullable<System.DateTime> IDDateOfIssue { get; set; }
        public string IDPlaceOfIssue { get; set; }
        public Nullable<System.Guid> TCountryID { get; set; }
        public Nullable<System.Guid> TProvinceID { get; set; }
        public Nullable<System.Guid> TDistrictID { get; set; }
        public string PAddress { get; set; }
        public Nullable<System.Guid> PCountryID { get; set; }
        public Nullable<System.Guid> PProvinceID { get; set; }
        public Nullable<System.Guid> PDistrictID { get; set; }
        public Nullable<System.Guid> NationalityID { get; set; }
        public string MarriageStatus { get; set; }
        public Nullable<double> Allowance { get; set; }
        public Nullable<System.Guid> JobTitleID { get; set; }
        public int? ProbationDay { get; set; }
        public string SkillLevel { get; set; }
        public Nullable<System.DateTime> DateHire { get; set; }
        public string NameEnglish { get; set; }
        public Nullable<System.Guid> BirthDayID { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<System.Guid> PlaceOfIssueID { get; set; }
        public Nullable<System.Guid> EducationLevelID { get; set; }
        public string Origin { get; set; }
        public Nullable<System.Guid> CurrencyID1 { get; set; }
        public string ImagePath { get; set; }
        public string PlaceWrokLast { get; set; }
        public Nullable<bool> IsRecruiting { get; set; }
        public string CodeCandidate { get; set; }
        public string PepolePresent { get; set; }
        public string SalaryPayment { get; set; }
        public string DateBirthOrther { get; set; }
        public Nullable<bool> IsDateBirthOrther { get; set; }
        public Nullable<bool> IsBlackList { get; set; }
        public string StatusHealth { get; set; }
        public Nullable<double> Allowance1 { get; set; }
        public Nullable<double> Allowance2 { get; set; }
        public Nullable<double> Allowance3 { get; set; }
        public Nullable<double> Allowance4 { get; set; }
        public Nullable<System.Guid> AllowanceID1 { get; set; }
        public Nullable<System.Guid> AllowanceID2 { get; set; }
        public Nullable<System.Guid> AllowanceID3 { get; set; }
        public Nullable<System.Guid> AllowanceID4 { get; set; }
        public Nullable<System.Guid> CurrencyID2 { get; set; }
        public Nullable<System.Guid> CurrencyID3 { get; set; }
        public Nullable<System.Guid> CurrencyID4 { get; set; }
        public Nullable<double> SalaryProbationary { get; set; }
        public string TimeWork { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public Nullable<double> DurationFailPrevious { get; set; }
        public Nullable<double> LevelEye { get; set; }
        public Nullable<double> GenaralHealth { get; set; }
        public Nullable<double> WriteTest { get; set; }
        public Nullable<double> Interview { get; set; }
        public string DiseaseListIDs { get; set; }
        public Nullable<int> LevelInterview { get; set; }
        public Nullable<System.DateTime> DateExam { get; set; }
        public string StatusView { get; set; }
        public string GenderView { get; set; }
        public string RankName { get; set; }
        public string JobVacancyName { get; set; }
        public string ReasonFailFilter { get; set; }

        public string E_UNIT { get; set; }
        public string E_DIVISION { get; set; }
        public string E_DEPARTMENT { get; set; }
        public string E_TEAM { get; set; }
        public string E_SECTION { get; set; }

        public string JobVacancyCode { get; set; }
        public string SourceAdsName { get; set; }
        public string MarriageStatusView { get; set; }
        public string EducationLevelName { get; set; }
        public string GraduateSchool { get; set; }
        public Nullable<System.DateTime> YearGraduation { get; set; }
        public string Specialisation { get; set; }


        public Nullable<System.DateTime> DateInterview1 { get; set; }
        public Nullable<System.DateTime> DateInterview2 { get; set; }
        public Nullable<System.DateTime> DateInterview3 { get; set; }
        public Nullable<System.DateTime> DateInterview4 { get; set; }
        public Nullable<System.DateTime> DateInterview5 { get; set; }
        public string LanguageCode1 { get; set; }
        public string LanguageCode2 { get; set; }
        public string LanguageCode3 { get; set; }
        public string LanguageCode4 { get; set; }
        public string LanguageCode5 { get; set; }
        public double? Score1_1 { get; set; }
        public double? Score1_2 { get; set; }
        public double? Score1_3 { get; set; }
        public string KQ1 { get; set; }

        public double? Score2_1 { get; set; }
        public double? Score2_2 { get; set; }
        public double? Score2_3 { get; set; }
        public string KQ2 { get; set; }

        public double? Score3_1 { get; set; }
        public double? Score3_2 { get; set; }
        public double? Score3_3 { get; set; }
        public string KQ3 { get; set; }

        public double? Score4_1 { get; set; }
        public double? Score4_2 { get; set; }
        public double? Score4_3 { get; set; }
        public string KQ4 { get; set; }

        public double? Score5_1 { get; set; }
        public double? Score5_2 { get; set; }
        public double? Score5_3 { get; set; }
        public string KQ5 { get; set; } 

    }
}
