using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HRM.Presentation.Hr.Models
{
    public class Hre_ProfilePortalModel
    {
        public string ProfileName { get; set; }
        //public string NameFamily { get; set; }
        //public string FirstName { get; set; }
        public string NameEnglish { get; set; }
        public string ImagePath { get; set; }
        public string CodeEmp { get; set; }
        public string CodeTax { get; set; }
        public string CodeAttendance { get; set; }
        //public string StatusSyn { get; set; }
        public Nullable<System.DateTime> DateHire { get; set; }
        public Nullable<System.DateTime> DateEndProbation { get; set; }
        public Nullable<System.DateTime> DateQuit { get; set; }
        //public string ResignDescription { get; set; }
        //public Nullable<System.Guid> CandidateID { get; set; }
        //public Nullable<System.Guid> WorkGroupID { get; set; }
        //public Nullable<System.Guid> OrgStructureID { get; set; }
        public string OrgStructureName { get; set; }
        //public Nullable<System.Guid> PositionID { get; set; }
        public string PositionName { get; set; }
        public Nullable<System.DateTime> DateOfEffect { get; set; }
        //public Nullable<System.Guid> CostCentreID { get; set; }
        public string LaborType { get; set; }
        public string WorkingPlace { get; set; }
        //public string Supervisor { get; set; }
        //public string SocialInsOldNo { get; set; }
        //public string SocialInsNo { get; set; }
        //public Nullable<System.DateTime> SocialInsDateReg { get; set; }
        //public Nullable<System.DateTime> SocialInsIssueDate { get; set; }
        //public string SocialInsIssuePlace { get; set; }
        //public string HealthInsNo { get; set; }
        //public Nullable<System.DateTime> HealthInsIssueDate { get; set; }
        //public Nullable<System.DateTime> HealthInsExpiredDate { get; set; }
        //public string HealthInsIssuePlace { get; set; }
        //public string HealthTreatmentPlace { get; set; }
        //public string HealthTreatmentProvince { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        //public Nullable<System.Guid> NationalityID { get; set; }
        public string NationalityName { get; set; }
        //public Nullable<System.Guid> EthnicID { get; set; }
        public string EthnicName { get; set; }
        //public Nullable<System.Guid> ReligionID { get; set; }
        public string BloodType { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public string IDNo { get; set; }
        public Nullable<System.DateTime> IDDateOfIssue { get; set; }
        public string IDPlaceOfIssue { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportDateOfExpiry { get; set; }
        public Nullable<System.DateTime> PassportDateOfIssue { get; set; }
        public string PassportPlaceOfIssue { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Cellphone { get; set; }
        public string HomePhone { get; set; }
        //public string BusinessPhone { get; set; }
        //public string PAStreet { get; set; }
        //public Nullable<System.Guid> PADistrictID { get; set; }
        //public Nullable<System.Guid> PACityID { get; set; }
        //public string TAStreet { get; set; }
        //public Nullable<System.Guid> TADistrictID { get; set; }
        //public Nullable<System.Guid> TACityID { get; set; }
        //public string StatusVerify { get; set; }
        //public Nullable<System.Guid> JobTitleID { get; set; }
        public string JobTitleName { get; set; }
        //public Nullable<System.Guid> TagID { get; set; }
        //public string LabourNo { get; set; }
        //public Nullable<System.DateTime> LabourIssueDate { get; set; }
        //public Nullable<System.Guid> PayrollGroupID { get; set; }
        public string PayrollGroupName { get; set; }
        //public string LaborBookNo { get; set; }
        //public Nullable<System.DateTime> LaborBookIssueDate { get; set; }
        //public Nullable<System.DateTime> RequestDate { get; set; }
        //public Nullable<System.Guid> EmpTypeID { get; set; }
        public string EmpTypeName { get; set; }
        //public Nullable<System.Guid> EducationLevelID { get; set; }
        public string EducationLevelName { get; set; }
        //public Nullable<System.Guid> ResReasonID { get; set; }
        public string MarriageStatus { get; set; }
        public string MarriageStatusView { get; set; }

        //public string ResignNo { get; set; }
        //public string Forte { get; set; }
        //public string TrainingSkill { get; set; }
        public string PromotionCondition { get; set; }
        //public string PromotionRequest { get; set; }
        //public Nullable<System.DateTime> DeadLineApprove { get; set; }
        //public string Notes2 { get; set; }
        public string Origin { get; set; }
        //public string ContactName1 { get; set; }
        //public string ContactName2 { get; set; }
        //public string ContactRelation1 { get; set; }
        //public string ContactRelation2 { get; set; }
        //public string ContactPhone1 { get; set; }
        //public string ContactPhone2 { get; set; }
        //public string ContactAddress1 { get; set; }
        //public string ContactAddress2 { get; set; }
        //public string ServerUpdate { get; set; }
        //public string ServerCreate { get; set; }
        //public string UserUpdate { get; set; }
        //public string UserCreate { get; set; }
        //public Nullable<System.DateTime> DateCreate { get; set; }
        //public Nullable<System.DateTime> DateUpdate { get; set; }
        //public Nullable<System.Guid> UserLockID { get; set; }
        //public Nullable<System.DateTime> DateLock { get; set; }
        //public Nullable<bool> IsDelete { get; set; }
        //public string IPCreate { get; set; }
        //public string IPUpdate { get; set; }
        //public string biography { get; set; }
        public string Notes { get; set; }
        //public Nullable<System.Guid> JobTitlePotentinalID { get; set; }
        //public Nullable<System.DateTime> DateFrom { get; set; }
        //public Nullable<System.DateTime> DateTo { get; set; }
        //public string LabourBookPlaceOfIssue { get; set; }
        public Nullable<bool> Smoke { get; set; }
        public string TypeOfVehicle { get; set; }
        //public string DrivingLisenceNo { get; set; }
        //public string StoredDocuments { get; set; }
        //public Nullable<System.Guid> LockerID { get; set; }
        public string LockerName { get; set; }
        //public string UnEmpInsNo { get; set; }
        //public Nullable<System.DateTime> UnEmpInsDateReg { get; set; }
        //public string UnEmpInsPlace { get; set; }
        //public Nullable<bool> ReceiveUnEmp { get; set; }
        //public Nullable<bool> ReceiveSocialIns { get; set; }
        //public Nullable<System.DateTime> ReceiveSocialInsDate { get; set; }
        //public string FileStore { get; set; }
        //public string FileAttach { get; set; }
        //public string HealthTreatmentPlaceCode { get; set; }
        //public Nullable<int> DayOfBirth { get; set; }
        //public Nullable<int> MonthOfBirth { get; set; }
        //public Nullable<int> YearOfBirth { get; set; }
        //public Nullable<bool> IsBlackList { get; set; }
        //public string HighSupervisor { get; set; }
        //public string Notes3 { get; set; }
        public Nullable<bool> IsDrivingLisence { get; set; }
        //public Nullable<int> ProbExtendDays { get; set; }
        //public Nullable<bool> IsHeadDept { get; set; }
        //public Nullable<bool> IsInsFollowUp { get; set; }
        //public string CommentIns { get; set; }
        //public Nullable<bool> ReceiveHealthIns { get; set; }
        //public Nullable<System.DateTime> ReceiveHealthInsDate { get; set; }
        //public Nullable<int> UnEmpInsCountMonthOld { get; set; }
        //public string Specialization { get; set; }
        //public Nullable<System.DateTime> ProbExtendDate { get; set; }
        //public Nullable<System.DateTime> SocialInsSubmitBookDate { get; set; }
        //public string SocialInsSubmitBookStatus { get; set; }
        //public string PasswordPaySlip { get; set; }
        //public string WorkPermitStatus { get; set; }
        //public string WorkPermitNo { get; set; }
        //public Nullable<System.DateTime> WorkPermitInsDate { get; set; }
        //public Nullable<System.DateTime> WorkPermitExpiredDate { get; set; }
        public Nullable<System.DateTime> DateOfIssuedTaxCode { get; set; }
        //public Nullable<System.DateTime> DateQuitSign { get; set; }
        public string LocationCode { get; set; }
        //public Nullable<System.Guid> SupervisorID { get; set; }
        public string SupervisorName { get; set; }
        //public Nullable<System.Guid> HighSupervisorID { get; set; }
        public string HighSupervisorName { get; set; }
        //public Nullable<System.Guid> WorkPlaceID { get; set; }
        //public string PasswordPaySliptDefault { get; set; }
        //public string SikillLevel { get; set; }
        public Nullable<System.DateTime> DateApplyAttendanceCode { get; set; }
        //public string FormType { get; set; }
        //public Nullable<System.Guid> PlaceOfIssueID { get; set; }
        //public string ResonBackList { get; set; }
        //public Nullable<System.DateTime> DatePrepare { get; set; }
        //public Nullable<System.Guid> PlaceOfBirthID { get; set; }
        //public Nullable<System.Guid> OrgLineDefaultID { get; set; }
        //public Nullable<System.Guid> ProducteLineDefaultID { get; set; }
        //public Nullable<System.Guid> ProvinceInsuranceID { get; set; }
        //public Nullable<System.DateTime> DateQuitRequest { get; set; }
        //public string ProfileSign { get; set; }
        //public string AddressEmergency { get; set; }
        //public Nullable<System.Guid> PassportPlaceID { get; set; }
        //public Nullable<System.Guid> VillageID { get; set; }
        //public Nullable<System.Guid> TAVillageID { get; set; }
        //public Nullable<int> Order { get; set; }
        //public string MarkColor { get; set; }
        //public Nullable<bool> IsExistentConcurrentPosition { get; set; }
        //public Nullable<double> PositionRate { get; set; }
        //public Nullable<System.Guid> PAddressID { get; set; }
        //public Nullable<System.Guid> TAddressID { get; set; }
        //public Nullable<bool> IsRegisterSocialIns { get; set; }
        //public Nullable<bool> IsRegisterHealthIns { get; set; }
        //public Nullable<bool> IsRegisterUnEmploymentIns { get; set; }

        public string PProvince { get; set; }
        public string PDistrict { get; set; }
        public string PAddress { get; set; }

        public string TProvince { get; set; }
        public string TDistrict { get; set; }
        public string TAddress { get; set; }
    }
}
